### ISSUE TITLE
Kubernetes error when trying to build SkyDNS via go get github.com/skynetservices/skydns

### ISSUE THREAD

**Issue by nightwolfzor** [skynetservices/skydns#103]
I get the following output when trying to compile SkyDNS running the command in the Readme;

go get github.com/skynetservices/skydns. I've tried removing all my cached packages to no effect. Ideas?

github.com/skynetservices/skydns
# github.com/skynetservices/skydns
./kubernetes.go:45: service.PortalIP undefined (type api.Service has no field or method PortalIP)
./kubernetes.go:46: service.Port undefined (type api.Service has no field or method Port)
./kubernetes.go:52: service.Port undefined (type api.Service has no field or method Port)
./kubernetes.go:52: service.Protocol undefined (type api.Service has no field or method Protocol)
./kubernetes.go:52: service.ProxyPort undefined (type api.Service has no field or method ProxyPort)
./kubernetes.go:54: service.ProxyPort undefined (type api.Service has no field or method ProxyPort)
./kubernetes.go:55: service.Protocol undefined (type api.Service has no field or method Protocol)
./kubernetes.go:60: service.Port undefined (type api.Service has no field or method Port)

**Comment by r0b1n** [comment]
Seems again mess with Kubernetes 
Check this commit https://github.com/GoogleCloudPlatform/kubernetes/commit/411666decb1b7d886e85b9a87c6b5ed4261dd7e5
Error I have got today
```
user@r0b2n:~$ go get github.com/skynetservices/skydns
# github.com/skynetservices/skydns/server
/usr/local/gopath/src/github.com/skynetservices/skydns/server/kubernetes.go:53: service.Spec.ProxyPort undefined (type api.ServiceSpec has no field or method ProxyPort)
/usr/local/gopath/src/github.com/skynetservices/skydns/server/kubernetes.go:55: service.Spec.ProxyPort undefined (type api.ServiceSpec has no field or method ProxyPort)
```
