### ISSUE TITLE
SkyDNS logo

### ISSUE THREAD

**Issue by jimmidyson** [skynetservices/skydns#109]
Any chance of knocking up a project logo?

**Comment by bketelsen** [comment]
PR's always accepted.
actually SkyNet had a logo.  Let me dig up a link

**Comment by bketelsen** [comment]
https://github.com/skynetservices/skynet/tree/master/documentation
Any of those would work.

**Comment by jimmidyson** [comment]
Thanks!

**Comment by bketelsen** [comment]
out of curiosity, what will you do with a logo?

**Comment by jimmidyson** [comment]
I'm working on Fabric8 (http://fabric8.io/v2) which basically is a management & integration platform for Kubernetes/OpenShift3. We provide a number of "apps" to install & to make things pretty in the UI apps can have icons/logos. I just added the SkyDNS logo to our SkyDNS "app".
