### ISSUE TITLE
SkyDNS behind kubernetes service: "reply from unexpected source"

### ISSUE THREAD

**Issue by jimmidyson** [skynetservices/skydns#110]
I have created a replication controller & service for SkyDNS on kubernetes. Accessing SkyDNS via the pod IP works fine, but when you try to access SkyDNS via the service IP you get the following response:

    ;; reply from unexpected source: 192.168.0.11#47494, expected 172.121.17.137#53

In this case, `192.168.0.11` is the host's IP address, `172.121.17.137` is the service IP address.

Any pointers?

**Comment by bketelsen** [comment]
upstream closed, closing.
