### ISSUE TITLE
Allow importing the skydns server as a package

### ISSUE THREAD

**Issue by smarterclayton** [skynetservices/skydns#113]
We'd like to embed SkyDNS in a single binary with [OpenShift](https://github.com/openshift/origin) as we do with etcd, so you can run in all-in-one mode.  Would you accept a pull request that moved the SkyDNS code to a subdir and left main.go in the root (for go install)?

**Comment by bketelsen** [comment]
Yes, we would.

**Comment by miekg** [comment]
Longer term it might be nicer to make a skydns package as a lib. Think we had the same issue open for skydns1.

**Comment by bketelsen** [comment]
We did.

On Mon, Jan 12, 2015 at 5:36 AM, Miek Gieben <notifications@github.com>
wrote:

> Longer term it might be nicer to make a skydns package as a lib. Think we
> had the same issue open for skydns1.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/skynetservices/skydns/issues/113#issuecomment-69552166>
> .
>



-- 

----
Brian Ketelsen
bketelsen <at> gmail <dot> com
