### ISSUE TITLE
Why do I need the -master flag?

### ISSUE THREAD

**Issue by MalteJ** [skynetservices/skydns#114]
Why do I need the `-master` flag when using kubernetes?
We have access to etcd and the master's IP should be available here.
So why do we have to provide it manually?
And where in the code is the `-master` flag? I cannot find it anywhere?

Thanks!
Malte

**Comment by bketelsen** [comment]
we're removing all the kubernetes support - the K8s team has added a skydns-kubernetes bridge that is much better than the crap I wrote.

**Comment by MalteJ** [comment]
Thank you :-)
