### ISSUE TITLE
Failure to return reply "dns: bad rdata"

### ISSUE THREAD

**Issue by budnyjj** [skynetservices/skydns#117]
Hello. I am trying to run skydns on the top of CoreOS.

To do so, I have downloaded docker image skynetservices/skydns and run it with following parameters:
```bash
docker run --rm -p 53:53/tcp -p 53:53/udp -p 8080:8080 --name skydns skynetservices/skydns -machines=172.17.42.1:4001 -addr=0.0.0.0:53 -domain=.
```

After that I have added record to etcd:
```bash
etcdctl --no-sync set /skydns/local/private_registry {"host":"192.168.122.20"}
```
and reverse PTR record for this domain:
```bash
etcdctl --no-sync set /skydns/arpa/in-addr/20/122/168/192 {"host":"private_registry"}
```

When I am trying to ping private_registry:
```bash
ping private_registry
```
all seems to work correctly, but when I am trying to curl docker private registry service, running on this host, I got five second delay and such messages in skydns logs:
```bash
[skydns] Jan 20 17:28:34.158 ERROR     | failure to return reply "dns: bad rdata"
[skydns] Jan 20 17:28:39.163 ERROR     | failure to return reply "dns: bad rdata"
[skydns] Jan 20 17:28:44.167 ERROR     | failure to return reply "dns: bad rdata"
```
I think that problem is in incorrect setup of reverse  PTR records but I don't know what exactly problem is.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[skydns] Failure to return reply "d..." ]
>Hello. I am trying to run skydns on the top of CoreOS.
>
>To do so, I have downloaded docker image skynetservices/skydns and run it with following parameters:
>```bash
>docker run --rm -p 53:53/tcp -p 53:53/udp -p 8080:8080 --name skydns skynetservices/skydns -machines=172.17.42.1:4001 -addr=0.0.0.0:53 -domain=.
>```
>
>After that I have added record to etcd:
>```bash
>etcdctl --no-sync set /skydns/local/private_registry {"host":"192.168.122.20"}
>```
>and reverse PTR record for this domain:
>```bash
>etcdctl --no-sync set /skydns/arpa/in-addr/20/122/168/192 {"host":"private_registry"}
>```
>
>When I am trying to ping private_registry:
>```bash
>ping private_registry
>```
>all seems to work correctly, but when I am trying to curl docker private registry service, running on this host, I got five second delay and such messages in skydns logs:
>```bash
>[skydns] Jan 20 17:28:34.158 ERROR     | failure to return reply "dns: bad rdata"
>[skydns] Jan 20 17:28:39.163 ERROR     | failure to return reply "dns: bad rdata"
>[skydns] Jan 20 17:28:44.167 ERROR     | failure to return reply "dns: bad rdata"
>```
>I think that problem is in incorrect setup of reverse  PTR records but I don't know what exactly problem is.


I think your problems is fix by:

```bash
$etcdctl --no-sync set /skydns/arpa/in-addr/20/122/168/192 {"host":"private_registry.skydns.local."}
```

I.e. make the name fully qualified.

I think not doing this by default is correct, but I could be convinced otherwise
:-)

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
Actually the README doesn't use the closing dot either. Should fix that as well.

Can you confirm adding a dot makes it work?

**Comment by miekg** [comment]
Hmmm, looking at the code I *do* already make the names fully qualified. 

Let's see if I can replicate  this.

**Comment by miekg** [comment]
Only now I see your `-domain=.`, that might makes things more interesting.. Is there *any* way you could tcp dump those replies?

**Comment by miekg** [comment]
Ah replicated.

**Comment by miekg** [comment]
Ah, yes.

;; QUESTION SECTION:
;private_registry.skydns.local.	IN	 A

;; AUTHORITY SECTION:
.	60	IN	SOA	ns.dns.. hostmaster.skydns.local. 1421784000 28800 7200 604800 60

Adding the domain twice, because you're using domain=.

**Comment by psi-4ward** [comment]
It also occours when a domain-part is too long
