### ISSUE TITLE
"go get github.com/skynetservices/skydns" fails in influxdb

### ISSUE THREAD

**Issue by evgeny-goldin** [skynetservices/skydns#120]
Hi,

Running `"go get github.com/skynetservices/skydns"' I'm getting the following error:

    /opt/golang/src/github.com/rcrowley/go-metrics/influxdb/influxdb.go:19: undefined: client.ClientConfig
    /opt/golang/src/github.com/rcrowley/go-metrics/influxdb/influxdb.go:38: undefined: client.Series
    /opt/golang/src/github.com/rcrowley/go-metrics/influxdb/influxdb.go:44: undefined: client.Series
    /opt/golang/src/github.com/rcrowley/go-metrics/influxdb/influxdb.go:52: undefined: client.Series
    /opt/golang/src/github.com/rcrowley/go-metrics/influxdb/influxdb.go:60: undefined: client.Series
    /opt/golang/src/github.com/rcrowley/go-metrics/influxdb/influxdb.go:70: undefined: client.Series
    /opt/golang/src/github.com/rcrowley/go-metrics/influxdb/influxdb.go:82: undefined: client.Series
    /opt/golang/src/github.com/rcrowley/go-metrics/influxdb/influxdb.go:93: undefined: client.Series
    /opt/golang/src/github.com/rcrowley/go-metrics/influxdb/influxdb.go:106: client.WriteSeries undefined (type *client.Client has no field or method WriteSeries)

**Comment by miekg** [comment]
Hmm :-( This is the third time something changed there. I'm getting a bit tired of it.
Feel like ripping influx support out of skydns all together.

**Comment by miekg** [comment]
travis also can't: https://travis-ci.org/skynetservices/skydns/builds/48481202

**Comment by miekg** [comment]
ah yes, `https://github.com/influxdb/influxdb/`, changed something again.
See https://github.com/rcrowley/go-metrics/issues/105

@bketelsen how many people you think use this? Last time I need to for `go-metrics` to fix this, I rather rip it out or find a better go lib to do this.

**Comment by bketelsen** [comment]
I don't have a sense for how many people use it, but agree completely.  Let's get rid of it and/or make it optional some how.

**Comment by miekg** [comment]
Optional is kinda hard, because sh*it ain't compiling.

I'll make a PR that rips this out.

**Comment by miekg** [comment]
https://github.com/skynetservices/skydns/pull/121

**Comment by miekg** [comment]
travis still fails nicely... :( can not get it to reproduce locally...

**Comment by miekg** [comment]
Going to ignore travis for a while.

**Comment by evgeny-goldin** [comment]
Thanks a million for an extremely fast fix, guys. Being a Go newbie (I just need to get SkyDNS up and running) I end up wondering if Go has a mechanism to depend on a released version of a third-party library? Or it's always the "latest" one, similar to Maven snapshots but for sources?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [skydns] "go get github.com/sky..." ]
>Thanks a million for an extremely fast fix, guys. Being a Go newbie (I just need to get SkyDNS up and running) I end up wondering if Go has a mechanism to depend on a released version of a third-party library? Or it's always the "latest" one, similar to Maven snapshots but for sources?

It's always the latest.

**Comment by evgeny-goldin** [comment]
That's extremely weird, coming from the world of dependency managers (Gradle, Maven, npm) where one can specify a released version or at least a Git tag. Thanks for clarification, Miek.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [skydns] "go get github.com/sky..." ]
>That's extremely weird, coming from the world of dependency managers (Gradle, Maven, npm) where one can specify a released version or at least a Git tag. Thanks for clarification, Miek.

Yeah :) There work around, like godep (i believe).

but the official stance is: keep it simple.

There are plenty of long, long discussions to be found on the go-nuts ML
archives

/Miek

--
Miek Gieben

**Comment by rogpeppe** [comment]
Please encourage upstream projects to maintain stable APIs. gopkg.in is a decent solution to that. Then at least "go get" should work - reproducible builds will still need something like godep or godeps though,
