### ISSUE TITLE
Use Godep

### ISSUE THREAD

**Issue by ecnahc515** [skynetservices/skydns#122]
It looks like a lot of your latest builds have been failing due to upstream changes.

I was wondering if you would care to use Godep to handle pinning dependencies in skydns. Id be willing to add the dependencies even, but right now I'm not sure if skydns is failing because of changes you made, or an upstream package did, or if configuration is wrong.

Going to the last 'stable' tag 2.0.1a, doesn't work because it wont build due to influx. Godep could handle these issues.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[skydns] Use Godep (#122)..." ]
>It looks like a lot of your latest builds have been failing due to upstream changes.
>
>I was wondering if you would care to use Godep to handle pinning dependencies in skydns. Id be willing to add the dependencies even, but right now I'm not sure if skydns is failing because of changes you made, or an upstream package did, or if configuration is wrong.

It's failing because of upstream changes (notably etcd), I ripped out influx
because they are really bad at keeping a stable api.

>Going to the last 'stable' tag 2.0.1a, doesn't work because it wont build due to influx. Godep could handle these issues.

I haven't played with godep myself, but I'm willing to consider a PR.

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[skydns] Use Godep (#122)..." ]
>It looks like a lot of your latest builds have been failing due to upstream changes.
>
>I was wondering if you would care to use Godep to handle pinning dependencies in skydns. Id be willing to add the dependencies even, but right now I'm not sure if skydns is failing because of changes you made, or an upstream package did, or if configuration is wrong.
>
>Going to the last 'stable' tag 2.0.1a, doesn't work because it wont build due to influx. Godep could handle these issues.

Btw, what's the downside of this? Do I now once in while need to go over these
deps and consider what the new safe versions should be?

/Miek

--
Miek Gieben

**Comment by bketelsen** [comment]
once we freeze at a version everything keeps working
if you want to pull in a new version you'd have to update, then freeze new versions
only downside is a little extra tooling client-side and in CI environments.  I use godep on all my work projects.

**Comment by ecnahc515** [comment]
Basically what was mentioned. The downside is that your vendoring dependencies essentially, but I think it's a pretty good trade-off, compared to completely unreliable builds.

**Comment by miekg** [comment]
I have to agree with this comment https://github.com/skynetservices/skydns/issues/120#issuecomment-72178991

http://labix.org/gopkg.in is much nicer, but requires upstream support (I think).

**Comment by ecnahc515** [comment]
Yeah I find gopkg.in to work, but doesn't work well for when you want to update your dependencies because now it's handled by the service. 

Also it's still doesn't give reproducible builds 100%.

**Comment by miekg** [comment]
I find it all very, very ugly. For starters: for some reason godep wants me to look a this giant `Godeps` directory with a capital 'G' no less.

**Comment by ecnahc515** [comment]
You don't really look at it. It's only for building.

**Comment by korya** [comment]
`gopkg.in` is an elegant solution. But it has a giant drawback: you cannot refer a specific commit, you can only refer a branch name formatted in a specific way. Yes, it enforces you to follow the semantic versioning conventions, but the main problem is that no one really follows this convention in golang community. At least, I did not see much projects compatible with `gopkg.in`. This kinda makes it completely useless. 

@miekg I agree `godep` is an ugly solution. Yes, especially the **G**odep dir name. But it works -- it provides you 100% reproducible builds.

**Comment by korya** [comment]
IMHO another huge advantage of `godep` is you finally can get rid of `GOPATH`; you just clone a repo anywhere, cd the cloned repo dir, and build it with `godep go build`:
```sh
git clone https://github.com/progrium/registrator
cd registrator
godep go build
```

For that feature I could forgive them even if they decided to call the dir `GODEP`.

**Comment by offlinehacker** [comment]
+1
