### ISSUE TITLE
usage of wildcard

### ISSUE THREAD

**Issue by takaomag** [skynetservices/skydns#127]
For example, digging against a DNS record with " * " is OK.
```
$ dig site-0.*.slave.mysql.dev-0.prj.local

; <<>> DiG 9.9.2-P2 <<>> site-0.*.slave.mysql.dev-0.prj.local
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 56333
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;site-0.*.slave.mysql.dev-0.prj.local.	IN	A

;; ANSWER SECTION:
site-0.*.slave.mysql.dev-0.prj.local. 288	IN	A	10.64.0.3
site-0.*.slave.mysql.dev-0.prj.local. 288	IN	A	10.64.0.2
site-0.*.slave.mysql.dev-0.prj.local. 288	IN	A	10.64.0.1

;; Query time: 2 msec
;; SERVER: 172.17.42.1#53(172.17.42.1)
;; WHEN: Wed Feb 11 17:18:19 2015
;; MSG SIZE  rcvd: 89
```

But, ping, ping6, curl and almost all client/server programs reject a hostname which includes "*".
```
$ ping site-0.*.slave.mysql.dev-0.prj.local
ping: unknown host site-0.*.slave.mysql.dev-0.prj.local
```
```
$ curl http://site-0.*.slave.mysql.dev-0.prj.local
curl: (6) Could not resolve host: site-0.*.slave.mysql.dev-0.prj.local
```

Is there any way to work around this issue ?

If there is no workaround, I think it would be nice to have a special(reserved) label which is treated as " * " by skydns.

For example, 
"site-0.**x-skydns-wc**.slave.mysql.dev-0.prj.local"
is treated as if
"site-0.*.slave.mysql.dev-0.prj.local"

**Comment by miekg** [comment]
Ah yes the brain dead standard library (when it comes to DNS). These are perfectly legal names, except libc thinks differently. In skydns we had the special label `any` for this case, would could bring that back. I rather have a special character, is libc stupid enough to let `+` slip through?

**Comment by miekg** [comment]
This is trivial to fix, but *what* to use to signal a wildcard. Anything we pick will clash with possible existing names. Skydns1 has `any` as said. I think I'll bring that back as well and add a cmdline flag where you can specify a wildcard label.

Playing a bit with `named` but that does not allow you to specify any special chars like % or ^ in a domain name at all.

**Comment by takaomag** [comment]
Sorry for the late reply.

Adding a command-line flag can allow user to specify own special wildcard label and can prevent name conflict. I feel that is nice !
 But in a large cluster, we might have to avoid querying such as "aaa.bbb.ccc.ddd.**any**.local." which may cause loading too many records from etcd.

**Comment by miekg** [comment]
I think this should *not* be configurable and we should just use `any`. So `*` == `any`.
