### ISSUE TITLE
DNS clients not always resolving correctly

### ISSUE THREAD

**Issue by mediocregopher** [skynetservices/skydns#128]
I'm running master of both etcd and skydns. I have the following setup in etcd (using `-domain foo` in skydns):

```
/skydns/foo/nodes/a-d/0 -> {"host":"8.8.8.8"}
/skydns/foo/nodes/a -> {"host":"a-d.nodes.foo"}
/skydns/foo/nodes/b-d/0 -> {"host":"8.8.4.4"}
/skydns/foo/nodes/b -> {"host":"b-d.nodes.foo"}
/skydns/foo/service/a -> {"host":"a.nodes.foo"}
/skydns/foo/service/b -> {"host":"b.nodes.foo"}
```

When attempting to ping `service.foo` I sometimes am get `ping: unknown host service.foo` and sometimes am able to ping successfully. Using wireshark I got some response packets for both cases.

**Pinged successfully**

![vpuj](https://cloud.githubusercontent.com/assets/933154/6219575/65c526a0-b5f9-11e4-8b74-0c3b59f2da0f.png)

**Unknown host**

![kypi](https://cloud.githubusercontent.com/assets/933154/6219589/8d17eb02-b5f9-11e4-94aa-71914d63f8dd.png)

I don't know much about how clients parse DNS, but the problem must be in how the CNAME entries are being ordered.

**Comment by miekg** [comment]
So if you would disable round-robin it would either always work, or always fail? (don't remember if we do it for cname as well)

In this case the (broken) libc will parse the reply and give you back an IP (nor not). We could group CNAME or something in this particular case.

Note that in the non-working case, to resolve `b-d.nodes.foo` the parser should go back one step, while in the working case it can just go forward.

**Comment by mediocregopher** [comment]
disabling round robin did work, the return almost always looks like this:

```
;; ANSWER SECTION:
service.foo.            3600    IN      CNAME   b.nodes.foo.
b.nodes.foo.            3600    IN      CNAME   b-d.nodes.foo.
b-d.nodes.foo.          3600    IN      A       8.8.4.4
service.foo.            3600    IN      CNAME   a.nodes.foo.
a.nodes.foo.            3600    IN      CNAME   a-d.nodes.foo.
a-d.nodes.foo.          3600    IN      A       8.8.8.8
```

although sometimes it gets switched up, with a being first.

The libc I'm using is just linux's standard glibc (albeit a newish version). I'm fine marking this as resolved since disabling round-robin works for my case, but I feel like other people are going to run into this since it happens on a pretty common setup.

Thanks for the help and the quick reply!

**Comment by miekg** [comment]
No, this is a bug in our code. We should not shuffle cname and just add them in the order we found them,  i.e. only shuffle A/AAAA.

**Comment by miekg** [comment]
Check the shuffle branch for a fix. I'm not sure if we now shuffle enough to make round-robin work in the normal case (I should check)

**Comment by mediocregopher** [comment]
Thanks for the fix! Unfortunately it didn't work for me :( I think the part of the code you changed only affected cache hits, but I don't have the cache enabled in my setup.

**Comment by miekg** [comment]
Ah yes. Fixed.

**Comment by mediocregopher** [comment]
Still not quite =/ It works more often, but still sometimes the ping fails. Here's a response that resulted in a failure:

![ezck](https://cloud.githubusercontent.com/assets/933154/6233109/c334f054-b69e-11e4-9cf1-266238125db3.png)

**Comment by miekg** [comment]
Can't see the trace, but I think I can guess why it does not work (i.e. some reason as before).
Hmmm, we either need to switch all CNAMEs with the A records. Or don't touch packets with CNAMEs.

**Comment by miekg** [comment]
I'm leaning against don't touch packets with more than 1 CNAME....

**Comment by mediocregopher** [comment]
if there's some kind of debugging you want to add that I can copy/paste to you I'd be happy to do so, just let me know

**Comment by miekg** [comment]
No that's fine. But what would you like to see here? Clearly libc can't deal with randomized packets (and CNAMEs). A randomizing answers is always a poor man's load balancing...

**Comment by mediocregopher** [comment]
So as far as what I'd like to see, currently if I turn off round-robin the results look like this:

```
service.foo.            3600    IN      CNAME   b.nodes.foo.
b.nodes.foo.            3600    IN      CNAME   b-d.nodes.foo.
b-d.nodes.foo.          3600    IN      A       8.8.4.4
service.foo.            3600    IN      CNAME   a.nodes.foo.
a.nodes.foo.            3600    IN      CNAME   a-d.nodes.foo.
a-d.nodes.foo.          3600    IN      A       8.8.8.8
```

And they pretty much always come back in that order. If, when round-robin was on, they came back with the first three entries half the time flipped with the second three I think that would fix the issue while still allowing for round-robin.

I understand that would probably require some kind of grouping that the code currently doesn't keep track of, so it would be a pretty big change. If you wanted to say that the short-term solution is to turn off round-robin I'd be ok with that, but I would say the docs should probably be updated to reflect that round-robin doesn't play nice with CNAMEs at the moment since I'm sure others are going to have this same issue.

Thanks again for looking into this so much, sorry it's being dragged out this far

**Comment by miekg** [comment]
Yes, I should also add text to the good. Good point.

Ok, pushed a change to the shuffle branch that leaves these kinds of packets alone.

**Comment by mediocregopher** [comment]
That fix didn't work :( It's still returning them shuffled up

**Comment by miekg** [comment]
uhm. Really? You did recompile?

**Comment by mediocregopher** [comment]
Well this is embarrassing, apparently I skipped that step, my bad :P

**Comment by miekg** [comment]
Ha! cool. I'll add a test as well before merging.

**Comment by errnoh** [comment]
I seem to be running into the same problem using commit 8898b33 (current master)

I created an A record for host.docker and three CNAME records that point to it. When round robin is enabled the records are in random order, which seems to cause ubuntu base image to fail half of the requests. When round robin is disabled the order stays the same each time and everything works.

```
;; ANSWER SECTION:
etcd.docker.		3600	IN	CNAME	host.docker.
host.docker.		3600	IN	A	192.168.99.100

root@f3a1c207169b:/# dig etcd.docker +short
192.168.99.100
host.docker.
root@f3a1c207169b:/# dig etcd.docker +short
host.docker.
192.168.99.100
root@f3a1c207169b:/# dig etcd.docker +short
host.docker.
192.168.99.100
root@f3a1c207169b:/# dig etcd.docker +short
192.168.99.100
host.docker.
root@f3a1c207169b:/# dig etcd.docker +short
host.docker.
192.168.99.100
root@f3a1c207169b:/# dig etcd.docker +short
192.168.99.100
host.docker.
```

**Comment by errnoh** [comment]
I moved to coredns, seems to be working fine over there. I'll let the above post stay here to let you guys know that it's still an issue.

**Comment by miekg** [comment]
Cool. I think just porting over this code: https://github.com/miekg/coredns/blob/master/middleware/loadbalance/loadbalance.go#L29 (i.e. put the cnames before the a/aaaa will make this work (for SkyDNS).

Really interested in CoreDNS feedback, 'cause right now the only feedback I have is from my dog food test for my personal domains (and that does not use the etcd middleware).
