### ISSUE TITLE
failure to forward request "dns: overflow unpacking uint32"

### ISSUE THREAD

**Issue by mediocregopher** [skynetservices/skydns#129]
Running both master and shuffle branch I get the following error

    failure to forward request "dns: overflow unpacking uint32"

when pinging `news.ycombinator.com`. It does not happen when I use dig, nor when I ping other sites. It does seem to affect chromium's resolving as well. The request fails completely when this happens.

I have a feeling the problem might actually be within your dns package and not this one specifically, so I can move this there if you want.

**Comment by mediocregopher** [comment]
I should probably also say I have master of `github.com/miekg/dns` pulled in as well

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [skydns] failure to forward req..." ]
>I should probably also say I have master of `github.com/miekg/dns` pulled in as well

That doesn't matter, is this sees little change.

Could capture a packet dump?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [skydns] failure to forward req..." ]
>I should probably also say I have master of `github.com/miekg/dns` pulled in as well

doing this with q (github.com/miekg/exdns/q), just works:

% ./q news.ycombinator.com
;; opcode: QUERY, status: NOERROR, id: 7858
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;news.ycombinator.com.  IN       A

;; ANSWER SECTION:
news.ycombinator.com.   69      IN      CNAME   news.ycombinator.com.cdn.cloudflare.net.
news.ycombinator.com.cdn.cloudflare.net.        69      IN      A       198.41.191.47
news.ycombinator.com.cdn.cloudflare.net.        69      IN      A       198.41.190.47

;; query time: 1584 �s, server: 127.0.1.1:53(udp), size: 221 bytes

/Miek

--
Miek Gieben

**Comment by mediocregopher** [comment]
http://gobin.io/CLDl

There's a packet capture of what happens when I do `ping news.ycombinator.com`

**Comment by miekg** [comment]
Those packets look completely normal to me. But i'll poke some more.

**Comment by miekg** [comment]
So I've copied some of packets out of the pcap in https://github.com/miekg/dns/commit/48ba40204d67f226b22279dcf94422e3b838fda1, but I can get it to overflow.

Are you sure you have captured all packets?

**Comment by mediocregopher** [comment]
I've managed to narrow this down some more, and have opened an issue at:

https://github.com/miekg/dns/issues/184

hopefully we can track it down there

**Comment by miekg** [comment]
Looks like the buffer used (in some cases) is too small to receive the whole answer.

**Comment by miekg** [comment]
Looking at the dump once more I don't see this large packet that is overflowing the buffer. Also EDNS0 is not set, so having a 512 bytes buffer is not unreasonable.

Would it be possible for you to try to capture the actual packets that create this overflow?

**Comment by miekg** [comment]
Also skydns uses the Exchange() function that does check the EDNS0 record and sizes the buffer according to the value in there...

**Comment by mediocregopher** [comment]
Here's another packet capture: http://gobin.io/pGVu

I'm having trouble getting it to happen over skydns explicitly, but if I create a simple dns proxy to my office's dns server using the dns package I'm able to reproduce pretty easily. Here's my client and server (not exactly the same as the ones I included in miekg/dns#184)

server: http://gobin.io/BQkt
client: http://gobin.io/QKLV

**Comment by miekg** [comment]
Yes, but in that server you just send a message which is too big for the client. A server MUST NOT do this. The big question here is why do we get a large packet back. Is cloudflare's DNS server doing this?

Do I make a mistake with compression somewhere?

**Comment by miekg** [comment]
I didn't set compression to true when returning from a cache hit.

**Comment by mediocregopher** [comment]
In this case our DNS server is certainly misconfigured, most of the data it sends back is simply not necessary. I'm working on getting that resolved.

Why would the server.go I posted be able to read the response from the remote dns server, but client.go wouldn't? In the example I posted they're both using the same method, `dns.Exchange`, and the response data is virtually the same (I think), the only difference is server.go reads from the remote server and client.go reads from server.go.

Sorry to drag this out, I'm building a dns proxy thing using your dns package as well, which is where I ran into this issue originally. Thanks for your help!

**Comment by miekg** [comment]
Np. You provided some excellent debugging here, so I'm glad to help.

> Why would the server.go I posted be able to read the response from the remote dns server, but 
> client.go wouldn't?

Because when the server reads it is compressed (and fits in 512 bytes) and when you return it to the client it is *not* compressed and overflows.

**Comment by mediocregopher** [comment]
Ah, that makes sense. Final question: In your fix (c864663) you're setting `m.Compress = true`, did you mean to use `m1` instead? You already set it on `m` near the top of the method, and `m1` is what's being written.

**Comment by miekg** [comment]
Yes.. Good catch! #damnit

**Comment by mediocregopher** [comment]
Cool, i'll close this up then (again). Thanks again for all the help :)
