### ISSUE TITLE
skydhcp

### ISSUE THREAD

**Issue by miekg** [skynetservices/skydns#135]
I think it makes sense to write a small dhcp server (or incorporate it directly in skydns) ala skydns. I.e. config is stored in etcd as a Service (with some extra fields) or some different al together.

When a client registers itself or in this case gets an address from skydhcp, skydhcp itself creates a Service entry so DNS resolution also works.

I have a feeling this is useful, but haven't really found a sweet spot yet. The only thing I can say is that I want it for my [Pi cluster](http://miek.nl/posts/2015/Feb/15/Setup%20Etcd%20on%20Raspberry%20Pi%20cluster/).

**Comment by bketelsen** [comment]
oh that's an awesome idea - if the dhcp server had pluggable config it might be useful in the docker / kubernetes orchestration world too (sorry this is where my head is most of the time)  cc/ @thockin @smarterclayton

**Comment by thockin** [comment]
I can imagine using this in the future, but we have no way to use it yet.

**Comment by smarterclayton** [comment]
Even better if we gave each container network namespace a MAC that was derived from the name and uid.

**Comment by miekg** [comment]
@bketelsen what do you mean with "pluggable config"? Config should live in etcd if you're asking that.

Let me try to find the time to hash out a decent design for this, i.e. a couple of paragraphs and iterate a bit on the Service side of things.

Having IPv6 support would be nice as well.

**Comment by bketelsen** [comment]
@miekg I mean the ability to choose different providers for DHCP.  For example - a default provider would use a configured subnet and default dns entries.  But an alternate provider might use some algorithm to assign IP addresses based on a pre-configured network topology.  I'm really talking out of my tail-end here... more wild speculation.  But making the configuration an Interface from the beginning would suffice.

**Comment by bketelsen** [comment]
https://github.com/krolaw/dhcp4

**Comment by miekg** [comment]
@bketelsen ah yes. That makes sense and is cool to have.

**Comment by miekg** [comment]
Let's call this a "design":

# SkyDHCP

SkyDHCP is a DHCP server that stores (or gets its content) from Etcd (or whatever backend). For the purpose here I'll use Etcd.

It can be used in conjunction with SkyDNS, i.e. SkyDHCP hands out an IP address and writes a `msg.Service` into Etcd, which can then be served by SkyDNS.

This DHCP server:

*   There is no config in Etcd, the server will 'calculate' the IP it hands out based on  a configurable algorithms, i.e. `-dhcp hash`, would enable is simple hashing on for instance the MAC address of the host asking for an IP. We want to make this easily pluggable, thus it will become an interface in the code.
*   The IP that is handed out is stored as a `msg.Service` in Etcd.
*   We give back the nameserver address of SkyDNS (or whatever nameserver you want to use)

## IPV4

There already is a [DHCP4](https://github.com/krolaw/dhcp4) package for Go. It would be nice to extend/add to this so IPV6 is supported as well. Small issue here is that IPv6 DHCP is completely different than V4.

## Code reuse

There is so much code we can re-use from SkyDNS that it actually makes sense to implement this
*in* SkyDNS. The only change we need in SkyDNS is to write to Etcd, but that is a simple change to
make and off course add the DHCP functionality.
