### ISSUE TITLE
Nameservers

### ISSUE THREAD

**Issue by akaspin** [skynetservices/skydns#136]
Question. My configuration:
```
/usr/bin/etcdctl set /skydns/config '{"dns_addr": "0.0.0.0:53", "domain":"tam.tam.", "nameservers": ["172.31.0.2:53","8.8.8.8:53","8.8.4.4:53"]}'
/opt/bin/skydns -machines=http://${COREOS_PRIVATE_IPV4}:4001 -local=%m.swarm.tam.tam -nameservers=172.31.0.2:53,8.8.8.8:53,8.8.4.4:53 -rcache=10000
```
But my logs trashed with:
```
Mar 02 02:04:39 ip-172-31-10-141.eu-west-1.compute.internal skydns:  2015/03/01 23:04:39 skydns: no nameservers defined or name too short, can not forward 
Mar 02 02:04:39 ip-172-31-10-141.eu-west-1.compute.internal skydns:  2015/03/01 23:04:39 skydns: no nameservers defined or name too short, can not forward 
Mar 02 02:04:50 ip-172-31-10-141.eu-west-1.compute.internal skydns:  2015/03/01 23:04:50 skydns: no nameservers defined or name too short, can not forward 
Mar 02 02:04:50 ip-172-31-10-141.eu-west-1.compute.internal skydns:  2015/03/01 23:04:50 skydns: no nameservers defined or name too short, can not forward 
Mar 02 02:04:50 ip-172-31-10-141.eu-west-1.compute.internal skydns:  2015/03/01 23:04:50 skydns: no nameservers defined or name too short, can not forward 
Mar 02 02:04:50 ip-172-31-10-141.eu-west-1.compute.internal skydns:  2015/03/01 23:04:50 skydns: no nameservers defined or name too short, can not forward 
Mar 02 02:04:50 ip-172-31-10-141.eu-west-1.compute.internal skydns:  2015/03/01 23:04:50 skydns: no nameservers defined or name too short, can not forward 
Mar 02 02:04:50 ip-172-31-10-141.eu-west-1.compute.internal skydns:  2015/03/01 23:04:50 skydns: no nameservers defined or name too short, can not forward 
Mar 02 02:04:52 ip-172-31-10-142.eu-west-1.compute.internal skydns:  2015/03/01 23:04:52 skydns: no nameservers defined or name too short, can not forward 
Mar 02 02:04:52 ip-172-31-10-142.eu-west-1.compute.internal skydns:  2015/03/01 23:04:52 skydns: no nameservers defined or name too short, can not forward 
Mar 02 02:04:52 ip-172-31-10-141.eu-west-1.compute.internal skydns:  2015/03/01 23:04:52 skydns: no nameservers defined or name too short, can not forward 
Mar 02 02:04:52 ip-172-31-10-141.eu-west-1.compute.internal skydns:  2015/03/01 23:04:52 skydns: no nameservers defined or name too short, can not forward 
Mar 02 02:04:52 ip-172-31-10-140.eu-west-1.compute.internal skydns:  2015/03/01 23:04:52 skydns: no nameservers defined or name too short, can not forward 
Mar 02 02:04:52 ip-172-31-10-140.eu-west-1.compute.internal skydns:  2015/03/01 23:04:52 skydns: no nameservers defined or name too short, can not forward 
Mar 02 02:04:53 ip-172-31-10-140.eu-west-1.compute.internal skydns:  2015/03/01 23:04:52 skydns: no nameservers defined or name too short, can not forward 
Mar 02 02:04:53 ip-172-31-10-140.eu-west-1.compute.internal skydns:  2015/03/01 23:04:52 skydns: no nameservers defined or name too short, can not forward
```
Where I wrong?

**Comment by miekg** [comment]
Does it work?

The name it is trying to forward has less labels than config.Ndots which 2 by default.
But it is better to make this 2 separate log lines.

**Comment by akaspin** [comment]
This works but trashing logs. We use slightly strange architecture. Every node in cluster has own SkyDNS. Thats very convenient because we don't use static IPs. All works but I'm concerned about these messages.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [skydns] Nameservers (#136)..." ]
>This works but trashing logs. We use slightly strange architecture. Every node in cluster has own SkyDNS. Thats very convenient because we don't use static IPs. All works but I'm concerned about these messages.

I've reworked the logging slightly. Those short names should not hit SkyDNS,
with extra logging you should be able to see what it is.

/Miek

--
Miek Gieben

**Comment by akaspin** [comment]
OK. skydns updated:
```
Mar 05 16:30:30 ip-172-31-10-140.eu-west-1.compute.internal skydns:  2015/03/05 13:30:30 skydns: can not forward, name too short (less than 2 labels): `localhost.' 
Mar 05 16:30:32 ip-172-31-10-140.eu-west-1.compute.internal skydns:  2015/03/05 13:30:32 skydns: can not forward, name too short (less than 2 labels): `localhost.' 
Mar 05 16:30:32 ip-172-31-10-140.eu-west-1.compute.internal skydns:  2015/03/05 13:30:32 skydns: can not forward, name too short (less than 2 labels): `localhost.'
```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [skydns] Nameservers (#136)..." ]
>OK. skydns updated:
>```
>Mar 05 16:30:30 ip-172-31-10-140.eu-west-1.compute.internal skydns:  2015/03/05 13:30:30 skydns: can not forward, name too short (less than 2 labels): `localhost.'
>Mar 05 16:30:32 ip-172-31-10-140.eu-west-1.compute.internal skydns:  2015/03/05 13:30:32 skydns: can not forward, name too short (less than 2 labels): `localhost.'
>Mar 05 16:30:32 ip-172-31-10-140.eu-west-1.compute.internal skydns:  2015/03/05 13:30:32 skydns: can not forward, name too short (less than 2 labels): `localhost.'
>```

Geh... That name should never show up at skydns. Something is wrong with your
(DNS) setup.

No `localhost` in `/etc/hosts` for instance? Localhost must(?) be locally
resolvable.

I could make skydns return 127.0.0.1 for this, but seems a bit silly...


--
Miek Gieben

**Comment by akaspin** [comment]
Yep :-) CoreOS is severe - no `/etc/hosts`. But:
```
Mar 05 17:31:32 ip-172-31-10-142.eu-west-1.compute.internal skydns:  2015/03/05 14:31:32 skydns: can not forward, name too short (less than 2 labels): `MI5.' 
Mar 05 17:31:32 ip-172-31-10-142.eu-west-1.compute.internal skydns:  2015/03/05 14:31:32 skydns: can not forward, name too short (less than 2 labels): `MI5.' 
Mar 05 17:31:32 ip-172-31-10-142.eu-west-1.compute.internal skydns:  2015/03/05 14:31:32 skydns: can not forward, name too short (less than 2 labels): `MI5.'
```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [skydns] Nameservers (#136)..." ]
>Yep :-) CoreOS is severe - no `/etc/hosts`. But:
>```
>Mar 05 17:31:32 ip-172-31-10-142.eu-west-1.compute.internal skydns:  2015/03/05 14:31:32 skydns: can not forward, name too short (less than 2 labels): `MI5.'
>Mar 05 17:31:32 ip-172-31-10-142.eu-west-1.compute.internal skydns:  2015/03/05 14:31:32 skydns: can not forward, name too short (less than 2 labels): `MI5.'
>Mar 05 17:31:32 ip-172-31-10-142.eu-west-1.compute.internal skydns:  2015/03/05 14:31:32 skydns: can not forward, name too short (less than 2 labels): `MI5.'
>```

Ghe, touche.

So these are "local" hostnames that don't get a default search path, and get
forwarded to the nearest nameserver.

That is actually broken. Is there an useful /etc/resolv.conf in coreos? Setting
ndots to 2?

/Miek

--
Miek Gieben

**Comment by akaspin** [comment]
CoreOS uses `systemd-resolved`. It's funny story because `systemd-resolved` prefers interface nameservers. But I need prepend skydns. So. For now I copy custom `resolv.conf` on start skydns:
```
$ cat  /etc/resolv.conf
nameserver 172.31.10.142 # <- cores private ip
nameserver 172.31.0.2
search eu-west-1.compute.internal
```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [skydns] Nameservers (#136)..." ]
>CoreOS uses `systemd-resolved`. It's funny story because `systemd-resolved` prefers interface nameservers. But I need prepend skydns. So. For now I copy custom `resolv.conf` on start skydns:
>```
>$ cat  /etc/resolv.conf
>nameserver 172.31.10.142 # <- cores private ip
>nameserver 172.31.0.2
>search eu-west-1.compute.internal
>```

Hmmm, these named like localhost or mi5 don't have any dots, so the search list
should be added to them. This prolly results in NXDOMAIN, so the name without
the search list is tried (and forwarded to skydns), and then skydns does the
right thing and drops the query.

I am not aware of a way to suppress that last query -- assuming I'm right about
the rest.

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
I think SkyDNS does the right thing here and if not there it not much I can do.

Can this be closed?
