### ISSUE TITLE
ttl parameter is ignored

### ISSUE THREAD

**Issue by Umkus** [skynetservices/skydns#137]
Hello and thanks for the effort. I'm trying to have a DNS record "expire" for a service, as it's described in the readme. But neither the config nor service level setting seem to have any effect. Services keep resolving. 

Specifically if I set both places to just 10 seconds nothing really changes after that time.
I'm thinking using `etcdctl's --ttl`  is what I really want, although it would be good to have a more straightforward doc.

**Comment by miekg** [comment]
The ttl you are referring too is the ttl on the dns record, it will not expire from etcd when that expires.

Indeed `etcdctl`'s ttl is the one you want.

PRs for better docs appreciated.

**Comment by Umkus** [comment]
Thanks!
