### ISSUE TITLE
set domain=. and DNS forwarding

### ISSUE THREAD

**Issue by chenzhiwei** [skynetservices/skydns#138]
Hi,

I want to use skydns to resolve `abcd` to `1.2.3.4`, as is known, `abcd` is not a fully qualified domain name. I found a way is to set the `-domain=.` in skydns.

But, setting `-domain=.` means the skydns is the authoritative DNS server of all domains. This will make the *right* domains can not be resolved, because there is no record in etcd of the *right* domains.

Are there any other ways to allow skydns resolve a pure string?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[skydns] set domain=. and DNS forwa..." ]
>Hi,
>
>I want to use skydns to resolve `abcd` to `1.2.3.4`, as is known, `abcd` is not a fully qualified domain name. I found a way is to set the `-domain=.` in skydns.
>
>But, setting `-domain=.` means the skydns is the authoritative DNS server of all domains. This will make the *right* domains can not be resolved, because there is no record in etcd of the *right* domains.
>
>Are there any other ways to allow skydns resolve a pure string?

No, not really.

What is it that you actually want to accomplish? Why doesn't abcd.abcd.local
work for you?

/Miek

--
Miek Gieben

**Comment by chenzhiwei** [comment]
Hi Miek,

Thanks for your reply.

I just want to make all the Docker containers can resolve their HOSTNAME each other.

Some applications MUST connect each other by using their HOSTNAME.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [skydns] set domain=. and DNS f..." ]
>Hi Miek,
>
>Thanks for your reply.
>
>I just want to make all the Docker containers can resolve their HOSTNAME each other.
>
>Some applications MUST connect each other by using their HOSTNAME.

man 5 resolv.conf

Set the value of 'domain' in /etc/resolv.conf to something sane and use that
as the suffix.

     domain  abcd.local.
     nameserver <ip-of-skydns>

Start skydns with -domain abcd.local. and add entries for server1.abcd.local.,
etc. Now your instances should be able to use server1.

/Miek

--
Miek Gieben

**Comment by chenzhiwei** [comment]
Thank you very much, this works ok for me.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [skydns] set domain=. and DNS f..." ]
>Thank you very much, this works ok for me.

     \o/

/Miek

--
Miek Gieben
