### ISSUE TITLE
Identical requests at exact same time causes timeouts

### ISSUE THREAD

**Issue by mediocregopher** [skynetservices/skydns#139]
So this is a fun one. If I make a tmux session with multiple panes and set synchronized panes (so all keystrokes go to all panes at the same time), and do a dig to SkyDNS for a domain SkyDNS will be forwarding for, the responses which come back for some of the digs will have the wrong request ID. Here's a screenshot:

http://gobin.io/VaBo

And here's a packet dump of the issue:

http://gobin.io/fCXX (might have to add the pcapng extension)

Looking at the packet capture it looks like there is a response to all four requests, but each response has the same request ID, so only one of the requests actually completes correctly. This happens both when requests are coming from the same host and when they all come from different hosts. It does not happen if the requests are slightly different. I made sure to confirm that this still happens on latest master of both skydns and the dns library.

Thanks!

**Comment by mediocregopher** [comment]
Just realized my screenshot isn't from the same run as the packet capture, they're to different domains. But the effect was basically the same. I can rerun it and get you matching ones if you need.

**Comment by miekg** [comment]
Haven't looked at the shots yet, but is this with forwarded named only or
with names skydns should be authoritative for?

**Comment by mediocregopher** [comment]
Forwarded only. Sorry, should have mentioned that.

**Comment by mediocregopher** [comment]
This fixed it, thanks!
