### ISSUE TITLE
Duplicate A records returned 

### ISSUE THREAD

**Issue by thockin** [skynetservices/skydns#149]
I'm continuing to play with multi-port kubernetes services in SkyDNS, and it ALMOST works as I expect.

For this example, I have a service called `multiport.th1` which I want an A record for (1.1.1.1) and which hosts 2 ports (http and https).

```
# etcdctl set /skydns/local/kubernetes/th1/multiport/http '{"host":"1.1.1.1", "port":80}'
{"host":"1.1.1.1", "port":80}

# etcdctl set /skydns/local/kubernetes/th1/multiport/https '{"host":"1.1.1.1", "port":443}'
{"host":"1.1.1.1", "port":443}

# dig @10.0.0.10 +noall +answer +additional multiport.th1.kubernetes.local A
multiport.th1.kubernetes.local.	3600 IN	A	1.1.1.1
multiport.th1.kubernetes.local.	3600 IN	A	1.1.1.1

# dig @10.0.0.10 +noall +answer +additional multiport.th1.kubernetes.local SRV
multiport.th1.kubernetes.local.	3600 IN	SRV	10 50 443 https.multiport.th1.kubernetes.local.
multiport.th1.kubernetes.local.	3600 IN	SRV	10 50 80 http.multiport.th1.kubernetes.local.
https.multiport.th1.kubernetes.local. 3600 IN A	1.1.1.1
http.multiport.th1.kubernetes.local. 3600 IN A	1.1.1.1
```

The troubling issue here is that 2 A records are returned.

**Comment by miekg** [comment]
Yes, those multiple ports should be suppressed. Note that I believe that properly written client will just grok this. Might be an issue with DNSSEC though, i.e. it should only sign one and I think SkyDNS will just sign the both of them.

**Comment by miekg** [comment]
Note: if you are fine with using IP addresses (as opposed to #144 where you wanted to have a name as the host) we don't need to StripTarget-hack

(although StripTarget still seems to be a good way of controlling things)

**Comment by thockin** [comment]
All along, all I *really* care about is getting the right result - whether
that uses IPs or hostnames doesn't really matter to me.  stripTarget still
lets me fine-tune the DNS responses, which is nice.

**Comment by miekg** [comment]
wait, with "The troubling issue here is that 2 A records are returned." you mean the `https` and `http` ones? I though you were mentioning the duplicate ones...

**Comment by thockin** [comment]
The duplicate ones.

```
# dig @10.0.0.10 +noall +answer +additional multiport.th1.kubernetes.local A
multiport.th1.kubernetes.local. 3600 IN A   1.1.1.1
multiport.th1.kubernetes.local. 3600 IN A   1.1.1.1
```

I just don't see any way to claim this is correct.  It might be VALID but it's weird.
