### ISSUE TITLE
A records and SRV records - too hacky?

### ISSUE THREAD

**Issue by thockin** [skynetservices/skydns#150]
I'm still just learning how to use SRV.  Hooray for wikipedia.  I apologize if I am dumb.  This seems to work:

```
# etcdctl set /skydns/local/kubernetes/th1/srvtst1/_tcp/_http '{"host":"1.1.1.1", "port":80}'
{"host":"1.1.1.1", "port":80}

# etcdctl set /skydns/local/kubernetes/th1/srvtst1/_tcp/_https '{"host":"1.1.1.1", "port":443}'
{"host":"1.1.1.1", "port":80}

# dig @10.0.0.10 +noall +answer +additional _http._tcp.srvtst1.th1.kubernetes.local SRV
_http._tcp.srvtst1.th1.kubernetes.local. 3600 IN SRV 10 100 80 _http._tcp.srvtst1.th1.kubernetes.local.
_http._tcp.srvtst1.th1.kubernetes.local. 3600 IN A 1.1.1.1

# dig @10.0.0.10 +noall +answer +additional _https._tcp.srvtst1.th1.kubernetes.local SRV
_https._tcp.srvtst1.th1.kubernetes.local. 3600 IN SRV 10 100 443 _https._tcp.srvtst1.th1.kubernetes.local.
_https._tcp.srvtst1.th1.kubernetes.local. 3600 IN A 1.1.1.1
```

Is that right?  Now I want to enable round-robin over that:

```
# etcdctl set /skydns/local/kubernetes/th1/srvtst1/_tcp/_http/pod1 '{"host":"1.1.1.1", "port":80}'
{"host":"1.1.1.1", "port":80}

# etcdctl set /skydns/local/kubernetes/th1/srvtst1/_tcp/_http/pod2 '{"host":"1.1.1.2", "port":80}'
{"host":"1.1.1.2", "port":80}

# dig @10.0.0.10 +noall +answer +additional _http._tcp.srvtst1.th1.kubernetes.local SRV
_http._tcp.srvtst1.th1.kubernetes.local. 3600 IN SRV 10 100 80 pod1._http._tcp.srvtst1.th1.kubernetes.local.
_http._tcp.srvtst1.th1.kubernetes.local. 3600 IN SRV 10 100 80 pod2._http._tcp.srvtst1.th1.kubernetes.local.
pod1._http._tcp.srvtst1.th1.kubernetes.local. 3600 IN A 1.1.1.1
pod2._http._tcp.srvtst1.th1.kubernetes.local. 3600 IN A 1.1.1.2
```

This looks great.  Now I want an A record for srvtst1.th1.kubernetes.local

```
# dig @10.0.0.10 +noall +answer +additional srvtst1.th1.kubernetes.local A
```

Nothing.  I guess that makes sense.  So now I write this:

```
# etcdctl set /skydns/local/kubernetes/th1/srvtst3/pod1 '{"host":"1.1.1.1", "port":80}'
{"host":"1.1.1.1", "port":80}

# etcdctl set /skydns/local/kubernetes/th1/srvtst3/pod2 '{"host":"1.1.1.2", "port":80}'
{"host":"1.1.1.2", "port":80}

# dig @10.0.0.10 +noall +answer +additional srvtst3.th1.kubernetes.local A
srvtst1.th1.kubernetes.local. 3600 IN	A	1.1.1.1
srvtst1.th1.kubernetes.local. 3600 IN	A	1.1.1.2
```

It's this last step that is confusing to me - it feels...dirty.  Is it right?  This is related to the conversation @miekg were having last week.  @smarterclayton too

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[skydns] A records and SRV records ..." ]
>I'm still just learning how to use SRV.  Hooray for wikipedia.  I apologize if I am dumb.  This seems to work:
>
>```
># etcdctl set /skydns/local/kubernetes/th1/srvtst1/_tcp/_http '{"host":"1.1.1.1", "port":80}'
>{"host":"1.1.1.1", "port":80}
>
># etcdctl set /skydns/local/kubernetes/th1/srvtst1/_tcp/_https '{"host":"1.1.1.1", "port":443}'
>{"host":"1.1.1.1", "port":80}
>
># dig @10.0.0.10 +noall +answer +additional _http._tcp.srvtst1.th1.kubernetes.local SRV
>_http._tcp.srvtst1.th1.kubernetes.local. 3600 IN SRV 10 100 80 _http._tcp.srvtst1.th1.kubernetes.local.
>_http._tcp.srvtst1.th1.kubernetes.local. 3600 IN A 1.1.1.1
>
># dig @10.0.0.10 +noall +answer +additional _https._tcp.srvtst1.th1.kubernetes.local SRV
>_https._tcp.srvtst1.th1.kubernetes.local. 3600 IN SRV 10 100 443 _https._tcp.srvtst1.th1.kubernetes.local.
>_https._tcp.srvtst1.th1.kubernetes.local. 3600 IN A 1.1.1.1
>```
>
>Is that right?  Now I want to enable round-robin over that:
>
>```
># etcdctl set /skydns/local/kubernetes/th1/srvtst1/_tcp/_http/pod1 '{"host":"1.1.1.1", "port":80}'
>{"host":"1.1.1.1", "port":80}
>
># etcdctl set /skydns/local/kubernetes/th1/srvtst1/_tcp/_http/pod2 '{"host":"1.1.1.2", "port":80}'
>{"host":"1.1.1.2", "port":80}
>
># dig @10.0.0.10 +noall +answer +additional _http._tcp.srvtst1.th1.kubernetes.local SRV
>_http._tcp.srvtst1.th1.kubernetes.local. 3600 IN SRV 10 100 80 pod1._http._tcp.srvtst1.th1.kubernetes.local.
>_http._tcp.srvtst1.th1.kubernetes.local. 3600 IN SRV 10 100 80 pod2._http._tcp.srvtst1.th1.kubernetes.local.
>pod1._http._tcp.srvtst1.th1.kubernetes.local. 3600 IN A 1.1.1.1
>pod2._http._tcp.srvtst1.th1.kubernetes.local. 3600 IN A 1.1.1.2
>```
>
>This looks great.  Now I want an A record for srvtst1.th1.kubernetes.local
>
>```
># dig @10.0.0.10 +noall +answer +additional srvtst1.th1.kubernetes.local A
>```
>
>Nothing.  I guess that makes sense.  So now I write this:

No this does not make sense. And the reason you are not getting a proper
response is because of pull request #145. Underscores are special in Etcd
(sadly). If I remove the underscores:

```
% dig @localhost +noall +answer -p 1053  th1.kubernetes.local A
th1.kubernetes.local.   3600    IN      A       1.1.1.2
th1.kubernetes.local.   3600    IN      A       1.1.1.1
```

>```
># etcdctl set /skydns/local/kubernetes/th1/srvtst3/pod1 '{"host":"1.1.1.1", "port":80}'
>{"host":"1.1.1.1", "port":80}
>
># etcdctl set /skydns/local/kubernetes/th1/srvtst3/pod2 '{"host":"1.1.1.2", "port":80}'
>{"host":"1.1.1.2", "port":80}
>
># dig @10.0.0.10 +noall +answer +additional srvtst3.th1.kubernetes.local A
>srvtst1.th1.kubernetes.local. 3600 IN	A	1.1.1.1
>srvtst1.th1.kubernetes.local. 3600 IN	A	1.1.1.2
>```
>
>It's this last step that is confusing to me - it feels...dirty.  Is it right?  This is related to the conversation @miekg were having last week.  @smarterclayton too
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/skynetservices/skydns/issues/150
/Miek

--
Miek Gieben

**Comment by SpComb** [comment]
Using RFC2782 SRV records *requires* you to use a indirect host names in the SRV records themselves, for multiple reasons. Using the new PR152 syntax for this example:

	$ etcdctl rm --recursive /skydns/local/skydns
	$ etcdctl set '/skydns/local/skydns/web/\_tcp/\_https/web2'    '{"host": "10.0.0.2", "port": 443}'
	{"host": "10.0.0.2", "port": 443}
	$ etcdctl set '/skydns/local/skydns/web/\_tcp/\_https/web1'    '{"host": "10.0.0.1", "port": 443}'
	{"host": "10.0.0.1", "port": 443}
	$ etcdctl set '/skydns/local/skydns/web/\_tcp/\_http/web1'    '{"host": "10.0.0.2", "port": 80}'
	{"host": "10.0.0.2", "port": 80}
	$ etcdctl set '/skydns/local/skydns/web/\_tcp/\_http/web1'    '{"host": "10.0.0.1", "port": 80}'
	{"host": "10.0.0.1", "port": 80}
	$ etcdctl set '/skydns/local/skydns/web/\_tcp/\_http/web2'    '{"host": "10.0.0.2", "port": 80}'
	{"host": "10.0.0.2", "port": 80}
	$ etcdctl ls --recursive -p /skydns/local/skydns
	/skydns/local/skydns/web/
	/skydns/local/skydns/web/\_tcp/
	/skydns/local/skydns/web/\_tcp/\_https/
	/skydns/local/skydns/web/\_tcp/\_https/web2
	/skydns/local/skydns/web/\_tcp/\_https/web1
	/skydns/local/skydns/web/\_tcp/\_http/
	/skydns/local/skydns/web/\_tcp/\_http/web1
	/skydns/local/skydns/web/\_tcp/\_http/web2

The correct SRV query will return names that are [incompatible](https://github.com/skynetservices/skydns/pull/145#issuecomment-91246950) with the glibc resolver (getaddrinfo will ignore any names containing `_`), and thus almost impossible to use in any application:

	$ dig +noall +answer +additional @localhost -p 1053 _http._tcp.web.skydns.local SRV
	_http._tcp.web.skydns.local. 10 IN      SRV     10 50 80 web1._http._tcp.web.skydns.local.
	_http._tcp.web.skydns.local. 10 IN      SRV     10 50 80 web2._http._tcp.web.skydns.local.
	web1._http._tcp.web.skydns.local. 10 IN A       10.0.0.1
	web2._http._tcp.web.skydns.local. 10 IN A       10.0.0.2

A recursive SRV query for a service-name with multiple services will give a mixture of incompatible protocols, which doesn't make any sense at all from an RFC2782 perspective:

	$ dig +noall +answer +additional @localhost -p 1053 web.skydns.local SRV
	web.skydns.local.       10      IN      SRV     10 25 443 web2._https._tcp.web.skydns.local.
	web.skydns.local.       10      IN      SRV     10 25 443 web1._https._tcp.web.skydns.local.
	web.skydns.local.       10      IN      SRV     10 25 80 web1._http._tcp.web.skydns.local.
	web.skydns.local.       10      IN      SRV     10 25 80 web2._http._tcp.web.skydns.local.
	web2._https._tcp.web.skydns.local. 10 IN A      10.0.0.2
	web1._https._tcp.web.skydns.local. 10 IN A      10.0.0.1
	web1._http._tcp.web.skydns.local. 10 IN A       10.0.0.1
	web2._http._tcp.web.skydns.local. 10 IN A       10.0.0.2

And a direct A query will work, but with duplicated results:

	$ dig +noall +answer +additional @localhost -p 1053 web.skydns.local A
	web.skydns.local.       10      IN      A       10.0.0.1
	web.skydns.local.       10      IN      A       10.0.0.2
	web.skydns.local.       10      IN      A       10.0.0.2
	web.skydns.local.       10      IN      A       10.0.0.1

See my [comment under PR145](https://github.com/skynetservices/skydns/pull/145#issuecomment-91246950) for a working example (although you will need to tweak the name syntax with PR152):

> [...] the service records and host-groups should be kept as separate trees:
>
>     /skydns/local/skydns/web/web1       {"host": "10.0.0.1"}
>     /skydns/local/skydns/web/web2       {"host": "10.0.0.2"}
>     /skydns/local/skydns/_tcp/_http/web1    {"host": "web1.web.skydns.local", "port": 80}
>     /skydns/local/skydns/_tcp/_http/web2    {"host": "web2.web.skydns.local", "port": 80}
>     /skydns/local/skydns/_tcp/_https/web1   {"host": "web1.web.skydns.local", "port": 443}
>     /skydns/local/skydns/_tcp/_https/web2   {"host": "web2.web.skydns.local", "port": 443}
>
> This way, you can still do non-SRV lookups against well-known ports (curl http://web.skydns.local/) as well as SRV lookups against well-known domains (srvlookup.lookup('http', domain='skydns.local')), all with an  unmodified skydns:
>
>     $ dig +short @localhost -p 1053 web.skydns.local A
>     10.0.0.2
>     10.0.0.1
>     $ dig +short @localhost -p 1053 _http._tcp.skydns.local SRV
>     10 50 80 web1.web.skydns.local.
>     10 50 80 web2.web.skydns.local.
>     $ dig +short @localhost -p 1053 _https._tcp.skydns.local SRV
>     10 50 443 web1.web.skydns.local.
>     10 50 443 web2.web.skydns.local.
>     $ dig +short @localhost -p 1053 web1.web.skydns.local A
>     10.0.0.1
>     $ dig +short @localhost -p 1053 web2.web.skydns.local A
>     10.0.0.2
>
> Note how SRV are canonically directly under the top-level domain, and not under any kind of service-specific domain. Indeed, the Python srvlookup function defaults to querying against the system's local domain name, and this is what systems such as e.g. Puppet recommend for SRV schemes .

**Comment by thockin** [comment]
I *think* I got most of that, and I came to some of the same conclusions, but I am not sure I followed how you avoided the duplicate A records.

Here are the results I want to achieve:
    * A svc.ns.kubernetes.local = [1.1.1.1, 2.2.2.2, 3.3.3.3]
    * A pod1.svc.ns.kubernetes.local = 1.1.1.1
    * A pod2.svc.ns.kubernetes.local = 2.2.2.2
    * A pod3.svc.ns.kubernetes.local = 3.3.3.3
    * SRV _http._tcp.svc.ns.kubernetes.local = svc.ns.kubernetes.local 80
    * SRV _https._tcp.svc.ns.kubernetes.local = svc.ns.kubernetes.local 443

I have practically achieved all of this with SkyDNS as it exists today.  I still have the duplicate A record problem.  #152 will break what I have done, so I will have to start over somewhat.  what am I doing wrong?

```
etcdctl rm --recursive /skydns/local/kubernetes/ns

etcdctl set /skydns/local/kubernetes/ns/svc/pod1/http '{"host":"1.1.1.1", "port":80}'
etcdctl set /skydns/local/kubernetes/ns/svc/pod1/https '{"host":"1.1.1.1", "port":443}'
etcdctl set /skydns/local/kubernetes/ns/svc/pod2/http '{"host":"2.2.2.2", "port":80}'
etcdctl set /skydns/local/kubernetes/ns/svc/pod2/https '{"host":"2.2.2.2", "port":443}'
etcdctl set /skydns/local/kubernetes/ns/svc/pod3/http '{"host":"3.3.3.3", "port":80}'
etcdctl set /skydns/local/kubernetes/ns/svc/pod3/https '{"host":"3.3.3.3", "port":443}'

etcdctl set /skydns/local/kubernetes/ns/svc/_tcp/_http/pod1 '{"host":"pod1.svc.ns.kubernetes.local", "port":80}'
etcdctl set /skydns/local/kubernetes/ns/svc/_tcp/_https/pod1 '{"host":"pod1.svc.ns.kubernetes.local", "port":443}'
etcdctl set /skydns/local/kubernetes/ns/svc/_tcp/_http/pod2 '{"host":"pod2.svc.ns.kubernetes.local", "port":80}'
etcdctl set /skydns/local/kubernetes/ns/svc/_tcp/_https/pod2 '{"host":"pod2.svc.ns.kubernetes.local", "port":443}'
etcdctl set /skydns/local/kubernetes/ns/svc/_tcp/_http/pod3 '{"host":"pod3.svc.ns.kubernetes.local", "port":80}'
etcdctl set /skydns/local/kubernetes/ns/svc/_tcp/_https/pod3 '{"host":"pod3.svc.ns.kubernetes.local", "port":443}'

dig @10.0.0.10 +noall +answer +additional +ignore pod1.svc.ns.kubernetes.local A
pod1.svc.ns.kubernetes.local. 3600 IN	A	1.1.1.1
pod1.svc.ns.kubernetes.local. 3600 IN	A	1.1.1.1

dig @10.0.0.10 +noall +answer +additional +ignore pod2.svc.ns.kubernetes.local A
pod2.svc.ns.kubernetes.local. 3600 IN	A	2.2.2.2
pod2.svc.ns.kubernetes.local. 3600 IN	A	2.2.2.2

dig @10.0.0.10 +noall +answer +additional +ignore pod3.svc.ns.kubernetes.local A
pod3.svc.ns.kubernetes.local. 3600 IN	A	3.3.3.3
pod3.svc.ns.kubernetes.local. 3600 IN	A	3.3.3.3

dig @10.0.0.10 +noall +answer +additional +ignore _http._tcp.svc.ns.kubernetes.local SRV
_http._tcp.svc.ns.kubernetes.local. 3600 IN SRV	10 33 80 pod2.svc.ns.kubernetes.local.
_http._tcp.svc.ns.kubernetes.local. 3600 IN SRV	10 33 80 pod3.svc.ns.kubernetes.local.
_http._tcp.svc.ns.kubernetes.local. 3600 IN SRV	10 33 80 pod1.svc.ns.kubernetes.local.

dig @10.0.0.10 +noall +answer +additional +ignore _https._tcp.svc.ns.kubernetes.local SRV
_https._tcp.svc.ns.kubernetes.local. 3600 IN SRV 10 33 443 pod1.svc.ns.kubernetes.local.
_https._tcp.svc.ns.kubernetes.local. 3600 IN SRV 10 33 443 pod2.svc.ns.kubernetes.local.
_https._tcp.svc.ns.kubernetes.local. 3600 IN SRV 10 33 443 pod3.svc.ns.kubernetes.local.
```

**Comment by SpComb** [comment]
Instead of these per-host-port records:

>    etcdctl set /skydns/local/kubernetes/ns/svc/pod1/http '{"host":"1.1.1.1", "port":80}'
>    etcdctl set /skydns/local/kubernetes/ns/svc/pod1/https '{"host":"1.1.1.1", "port":443}'

Register only one "host service" per host, i.e. instead of the above two records:

    etcdctl set /skydns/local/kubernetes/ns/svc/pod1 '{"host":"1.1.1.1"}'

Thus, whatever you're using to generate these needs to know  separately about both a) hosts b) services on those hosts

**Comment by miekg** [comment]
@thockin looks OK to me. Note the #153 hasn't been merged yet (in fact I just opened the PR).

**Comment by thockin** [comment]
@SpComb the reason I did that as two hosts was so that this query works, but it's not a strict REQUIREMENT for me:

```
# dig @10.0.0.10 +noall +answer +additional +ignore pod1.svc.ns.kubernetes.local SRV
pod1.svc.ns.kubernetes.local. 3600 IN	SRV	10 50 80 http.pod1.svc.ns.kubernetes.local.
pod1.svc.ns.kubernetes.local. 3600 IN	SRV	10 50 443 https.pod1.svc.ns.kubernetes.local.
http.pod1.svc.ns.kubernetes.local. 3600	IN A	1.1.1.1
https.pod1.svc.ns.kubernetes.local. 3600 IN A	1.1.1.1
```

**Comment by SpComb** [comment]
Dunno, that depends on how the client application doing SRV queries works. Once you're doing SRV queries like that, it's entirely up to you to define your own semantics, RFC2782 doesn't know anything about an SRV query like that, and e.g. python srvlookup can't be used to send a query like that.

What kind of client behaviour would involve enumerating all the service-ports on a given host via DNS? Note how the reply there doesn't actually tell you what protocol (http or https) the given port is. The most common case is finding all the host:port combos providing a known service/protocol under for a given domain.

At least for my own scheme, I don't think I would need to support queries like that.

**Comment by thockin** [comment]
You're right - it's mostly just human-friendly, especially in the kubernetes context

**Comment by thockin** [comment]
As long as #152 is not going in, this seems to work for me.  Closing this issue.  If #152 goes in, I'll have to start over :)
