### ISSUE TITLE
Performance fall after benchmark by queryperf

### ISSUE THREAD

**Issue by ZeaLoVe** [skynetservices/skydns#158]
Hello, I new to github ,also new to go ... I am now using skydns,etcd to do service discovery.
After I wrote my SDAgent for update DNS records. I need to know the performance of SKYDNS.

I run etcd on  3 VM(8G mem, 2*CPU) , and SKYDNS on one of them( could it be a problem?) 
I got the test result here ,and occur a strange problem.

These are my test results:
![image](https://cloud.githubusercontent.com/assets/10904090/7249146/bcd3e660-e84a-11e4-9803-e6f92c35ab89.png)

I see issues #74  and  there are big differences. even can't got 10K qps
And I came with the performance fall problem, when I start SKYDNS with ttl=0 ,rcache=100,rcache_ttl =5 ,use queryperf do 1000000 Records benchmark serveral times. It work well at beginning,about 5K qps, then it's became with QPS:300-600 . just like the rcache is gone (I guess). So I hope u can tell me, if there is a bug with rcache, or  something wrong with the configure of SKYDNS in my way ?

And I want know what env u run u SKYDNS can get 20K QPS .? Really thank you for your SKYDNS, good job! 

My SKYDNS start script:

curl -XPUT http://192.168.181.16:2379/v2/keys/skydns/config -d value='{"ttl":0,"rcache":100,"rcache-ttl":5}'
sleep 3
export ETCD_MACHINES='http://192.168.181.16:2379,http://192.168.181.17:2379,http://192.168.181.18:2379'
export SKYDNS_ADDR='192.168.181.16:53'
export SKYDNS_DOMAIN='.'
nohup ./skydns &

queryperf cmd:
./queryperf -d DNSRecords_1000000 -s 192.168.181.16
./queryperf -d DNSRecords_100000 -s 192.168.181.16
./queryperf -d DNSRecords_10000 -s 192.168.181.16

**Comment by miekg** [comment]
Thanks for doing this. I would also appreciate seeing a good profile to see where SkyDNS spends its time.

Regarding the run above:
* What's in the DNSRecords_xxx files? What names are you asking?
* The drop in performance is weird, my first guess (as in #74) would be GC, but of course there can also be a race in the cache not being refreshed or something like that...

**Comment by ZeaLoVe** [comment]
I run my sdagent to update 21 services interval, In file DNSRecords_XXX means XXX lines of DNS records for test (repeats of 21 services).  I run it in my VM with much processes on .So I will try to do the same test in a much pure env. If this happened again , I will try to get profile of it.
