### ISSUE TITLE
U may need to know this , and got the newest go-etcd API to make it correct

### ISSUE THREAD

**Issue by ZeaLoVe** [skynetservices/skydns#159]
go-etcd issues  https://github.com/coreos/go-etcd/pull/203

I took an afternoon debugging the skydns,etcd failover. Everytime I shutdown a etcd machine ,something wrong happend... sometimes got nothing from SKYDNS ,sometimes some of my sdagent can't update service..  I then checked the start script of my sdagent and skydns , found it that , the ETCD_MACHINES of are same with first one of SKYDNS and my sdagent which lost connection of etcd.

So... This is not a bug of SKYDNS ,but really confuse when in failover. hard to found the main problem.

**Comment by miekg** [comment]
Ok. Thanks for looking though. I can close it here?

**Comment by ZeaLoVe** [comment]
Yeah , of course .. but there always a trap before etcd API was fixed. You can close until it is done.
I updated the newest etcd API ,and build skydns , when I excute it , nothing output , it's weird , Could you help me to figure out why these happen? Thx

**Comment by ZeaLoVe** [comment]
@miekg Really the error of unworking skydns cause by the new etcd API ,I use go-etcd v2.0.0 rebuild it . I will pay attention to the bug of go-etcd , So you can close it here.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [skydns] U may need to know thi..." ]
>@miekg Really the error of unworking skydns cause by the new etcd API ,I use go-etcd v2.0.0 rebuild it . I will pay attention to the bug of go-etcd , So you can close it here.

awesome. Thanks!

/Miek

--
Miek Gieben

**Comment by ZeaLoVe** [comment]
Long time for trace, not finished yet ,but latest etcd API is work for my sdagent. They open a bug issue of forever block , you can close it here. The forver block of skydns is caused by SyncCluster with wrong setting of etcd. nothing with skydns.  I think I need to tell u about all above...so that's all,thx
