### ISSUE TITLE
ability to disable recursion

### ISSUE THREAD

**Issue by mischief** [skynetservices/skydns#160]
hi, i'm attempting to use skydns to serve my internet-visible services. unfortunately when skydns is exposed to the public internet, it acts as a recursing nameserver. it would be nice to have a config option to disable recursing and act as an authorative server only. even nicer would be ability to control this in a per-interface/listener or per-domain way.

**Comment by miekg** [comment]
you can easily disable the recursion. sorry afk, so hard time to give
details.

**Comment by mischief** [comment]
hm. i removed the nameservers from /skydns/config, and i can still dig @myserver google.com and get an A record. it's not clear from the documentation how this can be done. no rush, but keep me updated :-)

**Comment by miekg** [comment]
Yes...you can't. This is what's biting you: https://github.com/skynetservices/skydns/blob/master/server/config.go#L111

And that should be fixed, i.e. SkyDNS should not do that default. Prolly needs a little flag `-noresolv` that stops it from doing that.

**Comment by miekg** [comment]
Could you try the new `-no-rec` option in the `norec` branch?

**Comment by mischief** [comment]
@miekg sorry for the delay. busy weekend. let me build a docker image from `norec` and try it on my coreos cluster...

**Comment by miekg** [comment]
@mischief ..and?

**Comment by mischief** [comment]
@miekg seems like it works. dig @myserver google.com returns empty a records now.

**Comment by miekg** [comment]
cool. Will merge tomorrow. thanks.
