### ISSUE TITLE
Ability to add MX records 

### ISSUE THREAD

**Issue by Vinceveve** [skynetservices/skydns#161]
I'm searching where to add it but no way to find where to add an MX record.
Is it possible ? or planned ?

Thanks :)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[skydns] Ability to add MX records ..." ]
>I'm searching where to add it but no way to find where to add an MX record.
>
>Is it possible ? 

No.

> or planned ?

don't know... a SRV has a lot of simularies with an MX record, so I should not
be that hard.

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
how do actually envision this? Usually MX records are limited to < 5 records. If I would say all records in SkyDNS can become MX records you'll end up with a lot of (potential) records. Another thing would be to extend msg.Service with some kind of Type thingy. Both ways have drawbacks.

**Comment by Vinceveve** [comment]
my first idea was something like mx=true
This keep the logic of text records and cname auto sense
Plus it's easier to implement and lower memory footprint

For the 5 limit it's the sys admin problem not skydns one :)

**Comment by miekg** [comment]
Hmm, yeah, indeed for TXT I added a `Text` member to the `msg.Service` struct. So maybe a `Mail` boolean makes sense here.

**Comment by Vinceveve** [comment]
It's the only missing feature before having a fully functional DNS server with super easy etcd backend 
It's really great work !

**Comment by miekg** [comment]
Thanks :) 
Yes, `mx` records do complete the set of the "most-used-records".

**Comment by miekg** [comment]
MX records are now supported.

**Comment by Vinceveve** [comment]
Thanks Miek :)

I've just finished my own cluster and thinking again about the type variable
With the type field it become easy to use skydnss etcd to dynamically configure haproxy trough 
Confd
It can become a central registry for the inside and  outside cluster
What do you think ?
Sorry for beiing late and thanks again for the mx support :)

**Comment by miekg** [comment]
dunno, I don't really want to extend msg.Service any further.

Can you just use etcd directly for this?

**Comment by Vinceveve** [comment]
You're totally right, I will keep it separate. Thanks again !
