### ISSUE TITLE
Add Prometheus support

### ISSUE THREAD

**Issue by miekg** [skynetservices/skydns#171]

**Comment by smarterclayton** [comment]
An example of prometheus counters with skydns: https://github.com/openshift/origin/blob/83e2f09a36d6118cddb292e280ad1af2765b1831/pkg/dns/server.go#L64

**Comment by miekg** [comment]
ah, neat.

**Comment by miekg** [comment]
@smarterclayton I'm about to merge the prom branch which adds more complete support for Prometheus. It is done slightly separate from the current graphite support, mostly because I don't won't to deal with two graphing libs in SkyDNS. It also tracks more metrics.

**Comment by smarterclayton** [comment]
Great

**Comment by miekg** [comment]
Fixed with more metrics on the way.
