### ISSUE TITLE
skydns cannot use port as a string

### ISSUE THREAD

**Issue by saks** [skynetservices/skydns#172]
Hi there,

Just by accident I added host info with port as a string to etcd and skydns stopped resolving that domain at all.
skydns:
```shell
docker run --rm -p 153:53/udp -e ETCD_MACHINES='http://172.17.42.1:4001' \
skynetservices/skydns:2.2.0b -nameservers="8.8.8.8:" -verbose=true -addr=0.0.0.0:53
```
etcd:
```shell
docker run --rm -p 172.17.42.1:4001:4001 quay.io/coreos/etcd
```
add valid record:
```shell
curl -XPUT http://172.17.42.1:4001/v2/keys/skydns/local/skydns/east/production/rails/1 \
-d value='{"host":"service1.example.com","port":8080}'
```
try to resolve:
```bash
dig @127.0.0.1 -p 153 SRV +short rails.production.east.skydns.local
# => 10 100 8080 service1.example.com.
```
add another record but port as a string:
```bash
curl -XPUT http://172.17.42.1:4001/v2/keys/skydns/local/skydns/east/production/rails/2 \
-d value='{"host":"service1.example.com","port":"8080"}'
```
then:
```bash
dig @127.0.0.1 -p 153 SRV +short rails.production.east.skydns.local
```
returns nothing. With verbose flag I see just:
```bash
2015/05/06 10:41:51 skydns: received DNS Request for "rails.production.east.skydns.local." from "172.17.42.1:55595" with type 33
```
I'm not sure about the reason, why port is not supported as a string, but I'd really appreciate to see some error message about it. 
If there is any particular reason for not supporting port as a string, would be nice to know it from documentation.

Thanks!

**Comment by miekg** [comment]
PR for betters doc welcome.

You're right that skydns should logging something. Returning an error DNS message might not be appropriate as they are may be other services that just marshal fine. And SkyDNS should returns something always - so that's def. a bug.

**Comment by miekg** [comment]
Add a log.Printf in the marshalling branch. I'm a bit ambivalent on if we should care if the json is kaput. I think we should and the quickest way is to break responses. (which happened in the above case).

Anyway things like this should also be exported to a monitoring system, but I will do that when I get around to #171.
