### ISSUE TITLE
falling back to default configuration, could not read from etcd: 501: All the given peers are not reachable

### ISSUE THREAD

**Issue by underMoonLight** [skynetservices/skydns#179]
I have two virtual machines with CentOS 7. The first has good working skydns docker container. But, the second with latest skydns docker container has trouble. Couldn't resolve host.
[root@localhost ansible_pus]# curl -L http://127.0.0.1:4001/v2/keys/skydns/local/common/rabbitmq-1
{"action":"get","node":{"key":"/skydns/local/common/rabbitmq-1","value":"{\"host\":\"172.17.0.55\",\"port\":5672}","modifiedIndex":23,"createdIndex":23}}[root@localhost ansible_pus]#
[root@localhost ansible_pus]# curl rabbitmq-1.common.local:5672
curl: (6) Couldn't resolve host 'rabbitmq-1.common.local'
[root@localhost ansible_pus]#
At first sight all working correctly. But, when I looked up docker logs I see
[root@localhost ansible_pus]# docker logs skydns
2015/05/22 10:54:54 skydns: falling back to default configuration, could not read from etcd: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/skydns/config?quorum=false&recursive=false&sorted=false: dial tcp 127.0.0.1:4001: connection refused]) [0]
2015/05/22 10:54:54 skydns: ready for queries on local. for tcp://0.0.0.0:53 [rcache 0]
2015/05/22 10:54:54 skydns: ready for queries on local. for udp://0.0.0.0:53 [rcache 0]
On the first machine this logs
[root@localhost ansible_pus]# docker logs skydns
2015/05/22 11:38:26 skydns: falling back to default configuration, could not read from etcd: 100: Key not found (/skydns/config) [8]
2015/05/22 11:38:26 skydns: ready for queries on local. for tcp://0.0.0.0:53 [rcache 0]
2015/05/22 11:38:26 skydns: ready for queries on local. for udp://0.0.0.0:53 [rcache 0]
[root@localhost ansible_pus]#
I found https://registry.hub.docker.com/u/skynetservices/skydns/tags/manage/
and decided try another version.
2.3.0a (latest) runs with error.
2.2.1b runs with error.
2.2.1a runs with error.
2.2.0b good working.
The first virtual machin has 2.0.1d version skydns.

**Comment by miekg** [comment]
Building a new image locally, I see the same thing... Strange.

```
% docker run 1ab483c1d061 
2015/05/22 13:38:07 skydns: falling back to default configuration, could not read from etcd: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/skydns/config?quorum=false&recursive=false&sorted=false: dial tcp 127.0.0.1:4001: connection refused]) [0]
2015/05/22 13:38:07 skydns: ready for queries on skydns.local. for tcp://127.0.0.1:53 [rcache 0]
2015/05/22 13:38:07 skydns: ready for queries on skydns.local. for udp://127.0.0.1:53 [rcache 0]
```

**Comment by miekg** [comment]
Ah @anglerud to the rescue, you should start your docker with `--net host` so it can find the etcd instance.

**Comment by underMoonLight** [comment]
@miekg and @anglerud, big thanks! I start skydns docker container with --net host.

**Comment by miekg** [comment]
I'll add a line or two to the readme

**Comment by hagbarddenstore** [comment]
Hello there! I got this very same issue, even though I run with ```--net host```.

I'm running skydns:2.5.0b on CoreOS stable (647.2.0).

It doesn't matter if I use ```--net host``` or not, it still gives me this:

```
skydns: falling back to default configuration, could not read from etcd: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
```

I've tried with ```localhost```, ```127.0.0.1``` and ```10.5.9.88``` (Which is the IP of the machine) and they all give the same error. Gonna try with an older version.

**Comment by groob** [comment]
@miekg Running into same issue with versions newer than 2.2.0b 
I'm using etcd2 --proxy on 

For some reason, since 2.2.1a, -machines does not respect the address I specify and instead tries to connect to the etcd2 master node. 

Here is how I start skydns2:
```
/usr/bin/docker run --rm --name skydns --net host \
        skynetservices/skydns:2.2.0b \
        -machines=http://127.0.0.1:2379 \
        -addr 172.17.42.1:53 \
        -nameservers 8.8.8.8:53,8.8.4.4:53 \
        -verbose 'true' \
        -domain cluster.local.
```

From the logs, 
```
Jun 08 23:32:49 coreos-01 docker[8494]: Status: Image is up to date for skynetservices/skydns:2.2.0b
Jun 08 23:32:49 coreos-01 systemd[1]: Started SkyDNS.
Jun 08 23:32:50 coreos-01 docker[8501]: 2015/06/08 23:32:50 skydns: falling back to default configuration, could not read from etcd: 100: Key not found (/skydns) [5271]
Jun 08 23:32:50 coreos-01 docker[8501]: 2015/06/08 23:32:50 skydns: ready for queries on skydns.local. for tcp://172.17.42.1:53 [rcache 0]
Jun 08 23:32:50 coreos-01 docker[8501]: 2015/06/08 23:32:50 skydns: ready for queries on skydns.local. for udp://172.17.42.1:53 [rcache 0]
```


```
Jun 08 23:32:12 coreos-01 docker[8332]: Status: Downloaded newer image for skynetservices/skydns:2.2.1a
Jun 08 23:32:12 coreos-01 systemd[1]: Started SkyDNS.
Jun 08 23:32:13 coreos-01 docker[8425]: 2015/06/08 23:32:13 skydns: falling back to default configuration, could not read from etcd: 501: All the given peers are not reachable (failed to propose on members [https://104.236.11.231:2379] twice [last error: Get https://104.236.11.231:2379/v2/keys/skydns/config?quorum=false&recursive=false&sorted=false: remote error: bad certificate]) [0]
Jun 08 23:32:13 coreos-01 docker[8425]: 2015/06/08 23:32:13 skydns: ready for queries on skydns.local. for tcp://172.17.42.1:53 [rcache 0]
Jun 08 23:32:13 coreos-01 docker[8425]: 2015/06/08 23:32:13 skydns: ready for queries on skydns.local. for udp://172.17.42.1:53 [rcache 0]
```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [skydns] falling back to defaul..." ]
>@miekg Running into same issue with versions newer than 2.2.0b
>I'm using etcd2 --proxy on
>
>For some reason, since 2.2.1a, -machines does not respect the address I specify and instead tries to connect to the etcd2 master node.
>
>Here is how I start skydns2:
>```
>/usr/bin/docker run --rm --name skydns --net host \
>        skynetservices/skydns:2.2.0b \
>        -machines=http://127.0.0.1:2379 \
>        -addr 172.17.42.1:53 \
>        -nameservers 8.8.8.8:53,8.8.4.4:53 \
>        -verbose 'true' \
>        -domain cluster.local.
>```
>
>From the logs,
>```
>Jun 08 23:32:49 coreos-01 docker[8494]: Status: Image is up to date for skynetservices/skydns:2.2.0b
>Jun 08 23:32:49 coreos-01 systemd[1]: Started SkyDNS.
>Jun 08 23:32:50 coreos-01 docker[8501]: 2015/06/08 23:32:50 skydns: falling back to default configuration, could not read from etcd: 100: Key not found (/skydns) [5271]
>Jun 08 23:32:50 coreos-01 docker[8501]: 2015/06/08 23:32:50 skydns: ready for queries on skydns.local. for tcp://172.17.42.1:53 [rcache 0]
>Jun 08 23:32:50 coreos-01 docker[8501]: 2015/06/08 23:32:50 skydns: ready for queries on skydns.local. for udp://172.17.42.1:53 [rcache 0]
>```
>
>
>```
>Jun 08 23:32:12 coreos-01 docker[8332]: Status: Downloaded newer image for skynetservices/skydns:2.2.1a
>Jun 08 23:32:12 coreos-01 systemd[1]: Started SkyDNS.
>Jun 08 23:32:13 coreos-01 docker[8425]: 2015/06/08 23:32:13 skydns: falling back to default configuration, could not read from etcd: 501: All the given peers are not reachable (failed to propose on members [https://104.236.11.231:2379] twice [last error: Get https://104.236.11.231:2379/v2/keys/skydns/config?quorum=false&recursive=false&sorted=false: remote error: bad certificate]) [0]

ha, why do I see an SSL error here?

It could be that switch to Alpine Linux some root ca stuff changed and can't be
found...?
Ah yes:

skynetservices/skydns   2.2.1a              d2e8227f0800        4 weeks ago          17.65 MB
skynetservices/skydns   2.2.0b              a05dfe5ece5d        5 weeks ago          66.37 MB

The bigger one works, the smaller one (alpine) not. This surely is the reason,
except I don't know what to fix (yet)

Also *etcd* isself runs outside the docker image, so it should not be impacted.

/Miek

--
Miek Gieben

**Comment by groob** [comment]
@miekg You're seeing the ssl error because the original etcd cluster is running with TLS 

However, I'm connecting to th proxy on http://127.0.0.1:2379 which is not secured. 

I'm able to get/put to this URL without needing authentication using cURL

It's only when go-etcd runs SyncCluster() that this error happens.

**Comment by miekg** [comment]
I'm not even sure *why* skydns should call SyncCluster()... let me double check if that can be removed from the default code path.

**Comment by vmatekole** [comment]
r logs skydns
2015/06/21 09:11:21 skydns: falling back to default configuration, could not read from etcd: 100: Key not found (/skydns/config) [9]
2015/06/21 09:11:21 skydns: ready for queries on skydns.local. for tcp://127.0.0.1:53 [rcache 0]
2015/06/21 09:11:21 skydns: ready for queries on skydns.local. for udp://127.0.0.1:53 [rcache 0]

Hi,  I have same error on CoreOS 647.2.0 using etcd via Vagrant, additionally I am using -net host whilst running the following image built today. I can get/set values to etcd on the host:
``` Dockerfile
FROM golang
RUN go get github.com/skynetservices/skydns
WORKDIR $GOPATH/src/github.com/skynetservices/skydns
RUN go build -v
ENTRYPOINT ./skydns
