### ISSUE TITLE
Using quotes on the machines argument doesn't work

### ISSUE THREAD

**Issue by hagbarddenstore** [skynetservices/skydns#187]
Not sure if it's a bug in SkyDNS or perhaps the flags library, but if you use double or single quotes and an equals sign to set the CLI arguments it tries to use those URL encoded to pass to etcd.

Example:

```
skydns -machines='http://localhost:4001/'
skydns -machines="http://localhost:4001/"
```

The above doesn't work, the below does work:

```
skydns -machines=http://localhost:4001/
skydns -machines 'http://localhost:4001/'
skydns -machines "http://localhost:4001/"
```

This is related to my comment on #179 

I think the fix could be a simple strings.TrimPrefix() + strings.TrimSuffix or similar.

**Comment by miekg** [comment]
What do you mean? Those quotes are stripped by the shell, so they don't matter.
You see the equal sign popping up somewhere?

**Comment by hagbarddenstore** [comment]
That's the problem, they aren't escaped when there's an equal sign.

**Comment by miekg** [comment]
Can't reproduce: added a printf:

```
% ./skydns -machines="http://localhost:4001/"
[http://localhost:4001/]
```

**Comment by hagbarddenstore** [comment]
Hm, perhaps it's because of CoreOS then? I got this in my skydns.service file:

```
ExecStart=/usr/bin/docker run --net host -p 53:53 -p 53:53/udp --name skydns skynetservices/skydns -machines="http://${COREOS_PRIVATE_IPV4}:4001/"
```

And that doesn't work, but this does:

```
ExecStart=/usr/bin/docker run --net host -p 53:53 -p 53:53/udp --name skydns skynetservices/skydns -machines "http://${COREOS_PRIVATE_IPV4}:4001/"
```

So perhaps it's doing something with that to not escape the stuff that should be escaped. I recognise that this isn't really a bug as such, but still irritating as hell, so perhaps worth a mention in the documentation?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[skydns] Using quotes on the machin..." ]
>Not sure if it's a bug in SkyDNS or perhaps the flags library, but if you use double or single quotes and an equals sign to set the CLI arguments it tries to use those URL encoded to pass to etcd.
>
>Example:
>
>```
>skydns -machines='http://localhost:4001/'
>skydns -machines="http://localhost:4001/"
>```
>
>The above doesn't work, the below does work:
>
>```
>skydns -machines=http://localhost:4001/
>skydns -machines 'http://localhost:4001/'
>skydns -machines "http://localhost:4001/"
>```
>
>This is related to my comment on #179

You might be hitting #188, which is something I hadn't realized until this
moment...

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
systemd idiosyncrasy.
