### ISSUE TITLE
skydns doesn't forward query when no result is found in etcd

### ISSUE THREAD

**Issue by tonicbupt** [skynetservices/skydns#191]
I use skydns to hijack intra-net DNS query, if I set domain to `'xxx.com'` for skydns, if `'aaa.xxx.com'` is set in etcd, of course skydns will return the result from etcd to me, but if `'bbb.xxx.com'` is not set in etcd, skydns will not forward this query to the name servers I set in `nameservers`, I was wondering if this is designed to be or I did something wrong about it?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[skydns] skydns doesn't forward que..." ]
>I use skydns to hijack intra-net DNS query, if I set domain to `'xxx.com'` for skydns, if `'aaa.xxx.com'` is set in etcd, of course skydns will return the result from etcd to me, but if `'bbb.xxx.com'` is not set in etcd, skydns will not forward this query to the name servers I set in `nameservers`, I was wondering if this is designed to be or I did something wrong about it?

No, this is basically work-as-intended. SkyDNS is authoritative for xxx.com, so
if bbb.xxx.com does not exist that is the final answer and there should be no
need for SkyDNS to forward this to another server.

You might want to look into stubzones to see if that can help you.

/Miek

--
Miek Gieben

**Comment by tonicbupt** [comment]
thanks
