### ISSUE TITLE
[Question] Can skydns be an authoritative name server

### ISSUE THREAD

**Issue by pierreozoux** [skynetservices/skydns#193]
Hi,

I'm developing [indiepaas](https://github.com/indiepaas/indiepaas), yet another docker paas based on CoreOS. For now, I use namecheap to buy my domain names, and I use their name server that I configure though their API.

I'm looking for a solution based on etcd. I think skydns isn't the right answer, but I'd like to ask, just to be sure. It looks like the most advanced project from [the etcd project list](https://github.com/coreos/etcd/blob/master/Documentation/libraries-and-tools.md).

So my question is, can I set up skyDNS in such a way that it will be an authoritative name server for several domain names? From the documentation I understand it could do this for just one `domain`, stored in the `domain` configuration. I hope I'm wrong :) Please tell me.

If you have any ideas of any service that could do the job, it would be awesome. But from what I researched, I didn't find much.
The only viable alternative I see is to develop an etcd service that will watch the etcd db, and issue REST request on change to a [PowerDNS API](https://doc.powerdns.com/md/httpapi/README/).

Thanks for your help!

**Comment by miekg** [comment]
No, it is not a generic nameserver (although it comes close). It does *not* do multiple domains, see isseu #47. It should support enough records types (SOA, NS, MX, A, AAAA and SRV, DNSKEY) to be good enough as a generic nameserver, but YMMV (and I don't know of anybody who has done this).

I would love to see SkyDNS to be used in such a generic roll, but it needs code for which I currently don't have the time. Multiple domains should not be *too* hard, but is still a sizeable amount of work.

PowerDNS should be flexible enough for your needs I think, but PRs to SkyDNS are also welcome :)

**Comment by pierreozoux** [comment]
Ok, thanks for your clear answer.

I don't have any go knowledge at the moment, but I was thinking to do this generic etcd events to any REST as a side project to start learning on Go. Let's see if I have time!

Thanks again!
