### ISSUE TITLE
Understanding SkyDNS

### ISSUE THREAD

**Issue by jcmturner** [skynetservices/skydns#194]
Hi,

I'm a big fan of what SkyDNS is doing. I just wanted to check if I have understood the following limitations  correctly in the current version:

* It is not possible to be authoritative for mutliple domains
* It is not possible to edit the SOA record of a domain
* It is not possible to define more than one NS record for the domain (I have tested this and I cannot seem to achieve it)
* Currently restricted to the NS record being ns.dns.<domain>
* Restricts the use of using x{1,2,3...} as host names due to the way round robin is implemented

Are these correct or have I missed something somewhere? I just want to make sure I understand the current limitations correctly.

Also, with regards to the last point bullet point, would it not make more sense to implement round robin by adding a key/value like this:
etcdctl set /skydns/com/example/myroundrobin '{"host":["10.3.2.1","10.1.2.3"]}'
This way there would not be the limitation on using x{1,2,3...} names. Seems to make sense to me to trreat the round robin as one key.

Thanks.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[skydns] Understanding SkyDNS (#194..." ]
>Hi,
>
>I'm a big fan of what SkyDNS is doing. I just wanted to check if I have understood the following limitations  correctly in the current version:
>
>* It is not possible to be authoritative for mutliple domains

Nope, there is an issue open, but I don't have time work on it.

>* It is not possible to edit the SOA record of a domain

Nope, but should be easy to fixed, You can set the zone's hostmaster though.

>* It is not possible to define more than one NS record for the domain (I have tested this and I cannot seem to achieve it)

Really? You should be able to add more than 1, but if not, then that is a bug,
yes.

>* Currently restricted to the NS record being ns.dns.<domain>

yep. But see changing the SOA - I don't consider this too big of an issue
though.

>* Restricts the use of using x{1,2,3...} as host names due to the way round robin is implemented

really? While doing the round-robin SkyDNS does not look at the names itself, it
shuffles there place in the packet....


>Are these correct or have I missed something somewhere? I just want to make sure I understand the current limitations correctly.
>
>Also, with regards to the last point bullet point, would it not make more sense to implement round robin by adding a key/value like this:
>etcdctl set /skydns/com/example/myroundrobin '{"host":["10.3.2.1","10.1.2.3"]}'
>This way there would not be the limitation on using x{1,2,3...} names. Seems to make sense to me to trreat the round robin as one key.

The round robin works if there are multiple address to return it will just
shuffle them. I wonder how you got the idea that it is doing something funky?

/Miek

--
Miek Gieben

**Comment by jcmturner** [comment]
Thanks for the quick response.

I'll double check the issue with multiple nameservers and if confirmed I'll raise a specific issue on that with the details.

With regards to the round robin what I meant was that it would not be possible to have 2 A records such as:
x1.db.skydns.local  IN   A   10.1.2.3
x2.db.skydns.local  IN   A   10.2.3.4
My understanding is that this would be interpreted by skyDNS as a round robin for the name db.skydns.local. That is, you could not have A records with the host name being x1, x2 etc...
Not a huge deal but I was wondering if this limitation could be avoided if to set up a round robin you input a key like this:
etcdctl set /skydns/local/skydns/db '{"host":["10.3.2.1","10.1.2.3"]}'

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [skydns] Understanding SkyDNS (..." ]
>With regards to the round robin what I meant was that it would not be possible to have 2 A records such as:
>x1.db.skydns.local  IN   A   10.1.2.3
>x2.db.skydns.local  IN   A   10.2.3.4
>My understanding is that this would be interpreted by skyDNS as a round robin for the name db.skydns.local. That is, you could not have A records with the host name being x1, x2 etc...

Yes that is correct.

>Not a huge deal but I was wondering if this limitation could be avoided if to set up a round robin you input a key like this:
>etcdctl set /skydns/local/skydns/db '{"host":["10.3.2.1","10.1.2.3"]}'

No, this won't work as msg.Service only takes a single element as a host.

/Miek

--
Miek Gieben
