### ISSUE TITLE
Multiple NS records for a domain

### ISSUE THREAD

**Issue by jcmturner** [skynetservices/skydns#195]
Hi,

I seem to be unable to define more than one NS record for my domain.

I have skydns set up to be authoritative for a test domain "jtskydns.com" by starting skydns with the environment variable set `SKYDNS_DOMAIN="jtskydns.com"`

I add an NS record as below
`etcdctl set /skydns/com/jtskydns/dns/ns '{"host":"10.80.80.22"}'`

Dig gives me:
```
$ dig @127.0.0.1 NS jtskydns.com

; <<>> DiG 9.10.2-RedHat-9.10.2-1.fc22 <<>> @127.0.0.1 NS jtskydns.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 21412
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; QUESTION SECTION:
;jtskydns.com.			IN	NS

;; ANSWER SECTION:
jtskydns.com.		3600	IN	NS	ns.dns.jtskydns.com.

;; ADDITIONAL SECTION:
ns.dns.jtskydns.com.	3600	IN	A	10.80.80.22

;; Query time: 1 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Jun 17 21:31:56 BST 2015
;; MSG SIZE  rcvd: 67
```

I now try to add another NS record
`etcdctl set /skydns/com/jtskydns/dns/ns2 '{"host":"10.1.2.3"}'`

Querying with dig gives the same response as above. ns2 does not appear as an NS record.

**Comment by miekg** [comment]
Documentation error, nameserver should be *under* `ns.dns...` i.e. `ns1.ns.dns...` and `ns2.ns.dns...`

**Comment by jcmturner** [comment]
Thanks this clarifies things and this works well.
