### ISSUE TITLE
2.5.1a commit not on master branch?

### ISSUE THREAD

**Issue by thockin** [skynetservices/skydns#198]
I see a release tagged 2.5.1a, but I can't figure out where that commit is - it is not in the commit stream of the master branch.  What am I doing wrong?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[skydns] 2.5.1a commit not on maste..." ]
>I see a release tagged 2.5.1a, but I can't figure out where that commit is - it is not in the commit stream of the master branch.  What am I doing wrong?

Ah, no my fault. Will fix today as I will push some more metrics and then will
tag a new release.

/Miek

--
Miek Gieben

**Comment by thockin** [comment]
I thought I was going nuts.  Please don't retarget that tag - I just
vendored that gitsha :)

**Comment by miekg** [comment]
ack. i will use my imagination and invent a new tag :)

**Comment by miekg** [comment]
2.5.2a tagged and docker images pushed.
