### ISSUE TITLE
No answer on DNS query

### ISSUE THREAD

**Issue by Dynom** [skynetservices/skydns#204]
Hi,

I'm a noob when it comes to DNS and I can't seem SkyDNS to work.

I use the `skynetservices/skydns` docker image, and run it like so:
```
/usr/bin/docker run --net=host \
--rm \
-it \
-e "ETCD_MACHINES=http://10.129.113.97:2379,http://10.129.113.97:4001" \
-e "SKYDNS_NAMESERVERS=8.8.8.8:53,8.8.4.4:53" \
-e "SKYDNS_ADDR=10.129.113.97:53" \
-p 10.129.113.97:53:53/udp  \
skynetservices/skydns \
-verbose -discover
```

I'm using --net=host to make sure that SkyDNS can reach Etcd. I might change this later, but for now that part seems to work. As you'll see later I actually use `127.0.0.1:53` due to the config in Etcd.

My Etcd2 config:
```
$ etcdctl get /skydns/config
{"no-rec": true, "ttl": 60, "dns_addr": "127.0.0.1:53"}
```

I've added several hosts:
```
$ etcdctl ls /skydns/local/skydns/hutsefluts
/skydns/local/skydns/hutsefluts/1
/skydns/local/skydns/hutsefluts/3
/skydns/local/skydns/hutsefluts/5
/skydns/local/skydns/hutsefluts/2
/skydns/local/skydns/hutsefluts/6
/skydns/local/skydns/hutsefluts/4
/skydns/local/skydns/hutsefluts/7
```

With the key's similar (different IP's) to:
```
$ etcdctl get /skydns/local/skydns/hutsefluts/1
{"host": "10.129.112.176", "ttl": "30", "targetstrip": 1 }
```

When I `dig`, I get:
```
dig @127.0.0.1 SRV 1.recommendation.skydns.local

; <<>> DiG 9.10.2-P1-RedHat-9.10.2-2.P1.fc22 <<>> @127.0.0.1 SRV 1.recommendation.skydns.local
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 23090
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;1.recommendation.skydns.local.	IN	SRV

;; AUTHORITY SECTION:
skydns.local.		60	IN	SOA	ns.dns.skydns.local. hostmaster.skydns.local. 1436533200 28800 7200 604800 60

;; Query time: 1 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Fri Jul 10 13:15:53 UTC 2015
;; MSG SIZE  rcvd: 101
```

There must be something obvious that I'm missing, but I haven't the foggiest. I'm assuming SkyDNS can't find the key? But I have a hard time debugging the queries, SkyDNS isn't very informative about why it's not returning an answer.

When I try the somewhat more magical `ns.dns.skydns.local`
```
$ etcdctl get /skydns/local/skydns/dns/ns/ns1
{ "host": "127.0.0.1" }
```

I get an answer:
```
$ dig @127.0.0.1 A ns.dns.skydns.local | grep 127.0.0.1
; <<>> DiG 9.10.2-P1-RedHat-9.10.2-2.P1.fc22 <<>> @127.0.0.1 A ns.dns.skydns.local
ns.dns.skydns.local.	60	IN	A	127.0.0.1
```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[skydns] No answer on DNS query (#2..." ]
>Hi,
>
>I'm a noob when it comes to DNS and I can't seem SkyDNS to work.
>
>I use the `skynetservices/skydns` docker image, and run it like so:
>```
>/usr/bin/docker run --net=host \
>--rm \
>-it \
>-e "ETCD_MACHINES=http://10.129.113.97:2379,http://10.129.113.97:4001" \
>-e "SKYDNS_NAMESERVERS=8.8.8.8:53,8.8.4.4:53" \
>-e "SKYDNS_ADDR=10.129.113.97:53" \
>-p 10.129.113.97:53:53/udp  \
>skynetservices/skydns \
>-verbose -discover
>```
>
>I'm using --net=host to make sure that SkyDNS can reach etcd2 I might change this later, but for now that part seems to work.
>
>My etcd2 config:
>```
>$ etcdctl get /skydns/config
>{"no-rec": true, "ttl": 60, "dns_addr": "127.0.0.1:53"}
>```

You've enabled SKYDNS_NAMESERVERS, but also "no-rec". No-rec negates the use of
external nameservers.

>I've added several hosts:
>```
>$ etcdctl ls /skydns/local/skydns/hutsefluts
>/skydns/local/skydns/hutsefluts/1
>/skydns/local/skydns/hutsefluts/3
>/skydns/local/skydns/hutsefluts/5
>/skydns/local/skydns/hutsefluts/2
>/skydns/local/skydns/hutsefluts/6
>/skydns/local/skydns/hutsefluts/4
>/skydns/local/skydns/hutsefluts/7
>```
>
>With the key's similar to:
>```
>$ etcdctl get /skydns/local/skydns/hutsefluts/1
>{"host": "10.129.112.176", "ttl": "30", "targetstrip": 1 }
>```

without a `"port":<something>` it will never become a SRV record.

>
>When I `dig`, I get:
>```
>dig @127.0.0.1 SRV 1.recommendation.skydns.localal

Where does 'recommendation' come from?

```
dig A hutsefluts.skydns.local
```

should give you something.

**Comment by Dynom** [comment]
Thanks for the reply, I was updating my post with a bit more information. Please check the last part of my update again for a bit more info.

Recommendation is another host I have running:
```
etcdctl get /skydns/local/skydns/recommendation/3
{"host": "10.129.112.210", "ttl": "30", "port": 3000 }
```
```
$ dig @127.0.0.1 SRV 3.recommendation.skydns.local

; <<>> DiG 9.10.2-P1-RedHat-9.10.2-2.P1.fc22 <<>> @127.0.0.1 SRV 3.recommendation.skydns.local
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 27223
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;3.recommendation.skydns.local.	IN	SRV

;; Query time: 5 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Fri Jul 10 14:29:04 UTC 2015
;; MSG SIZE  rcvd: 47
```

```
$ dig @127.0.0.1 SRV recommendation.skydns.local

; <<>> DiG 9.10.2-P1-RedHat-9.10.2-2.P1.fc22 <<>> @127.0.0.1 SRV recommendation.skydns.local
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 47673
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;recommendation.skydns.local.	IN	SRV

;; Query time: 7 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Fri Jul 10 14:29:21 UTC 2015
;; MSG SIZE  rcvd: 45
```

**Comment by Dynom** [comment]
I don't get an A answer also:
```
$ dig A hutsefluts.skydns.local

; <<>> DiG 9.10.2-P1-RedHat-9.10.2-2.P1.fc22 <<>> A hutsefluts.skydns.local
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 55595
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;hutsefluts.skydns.local.	IN	A

;; AUTHORITY SECTION:
skydns.local.		60	IN	SOA	ns.dns.skydns.local. hostmaster.skydns.local. 1436536800 28800 7200 604800 60

;; Query time: 18 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Fri Jul 10 14:29:49 UTC 2015
;; MSG SIZE  rcvd: 95
```

**Comment by Dynom** [comment]
> You've enabled SKYDNS_NAMESERVERS, but also "no-rec". No-rec negates the use of
external nameservers.

Yeah, that was a test I was running, to make sure that I was actually getting an answer from SkyDNS. I'll remove that once I get everything up and running. Thanks for the tip though!

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [skydns] No answer on DNS query..." ]
>Thanks for the reply, I was updating my post with a bit more information. Please check the last part of my update again for a bit more info.
>
>Recommendation is another host I have running:
>```
>etcdctl get /skydns/local/skydns/recommendation/3
>{"host": "10.129.112.210", "ttl": "30", "port": 3000 }
>```
>```
>$ dig @127.0.0.1 SRV 3.recommendation.skydns.local

are you sure skydns can access etcd?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[skydns] No answer on DNS query (#2..." ]
>Hi,
>
>I'm a noob when it comes to DNS and I can't seem SkyDNS to work.
>
>I use the `skynetservices/skydns` docker image, and run it like so:

what does docker logs say?

**Comment by Dynom** [comment]
> are you sure skydns can access etcd?
Quite certain. If I change a value to something illegal, SkyDNS complains, e.g.:

```
$ etcdctl set /skydns/config '{"no-rec": "true", "ttl": 60, "dns_addr": "6666"}'
{"no-rec": "true", "ttl": 60, "dns_addr": "6666"}
```

```
/usr/bin/docker run --net=host --rm -it -e "ETCD_MACHINES=http://10.129.113.97:2379" -e "SKYDNS_NAMESERVERS=8.8.8.8:53,8.8.4.4:53" skynetservices/skydns -verbose
2015/07/10 14:42:43 skydns: ready for queries on skydns.local. for tcp://6666 [rcache 0]
2015/07/10 14:42:43 skydns: ready for queries on skydns.local. for udp://6666 [rcache 0]
2015/07/10 14:42:43 skydns: missing port in address 6666
```

**Comment by Dynom** [comment]
> what does docker logs say?
I run it interactive right now. The logs say only:

Starting SkyDNS:
```
/usr/bin/docker run --net=host --rm -it -e "ETCD_MACHINES=http://10.129.113.97:2379" -e "SKYDNS_NAMESERVERS=8.8.8.8:53,8.8.4.4:53" skynetservices/skydns -verbose
```

Performing a lookup:
```
$ dig @127.0.0.1 A hutsefluts.skydns.local
```

The logs:
```
2015/07/10 14:45:00 skydns: ready for queries on skydns.local. for tcp://127.0.0.1:53 [rcache 0]
2015/07/10 14:45:00 skydns: ready for queries on skydns.local. for udp://127.0.0.1:53 [rcache 0]
2015/07/10 14:45:05 skydns: received DNS Request for "hutsefluts.skydns.local." from "127.0.0.1:35083" with type 1
```

**Comment by Dynom** [comment]
And the "magical" lookup does seem to work:

```
$ dig @127.0.0.1 A ns.dns.skydns.local | grep 127.0.0.1
; <<>> DiG 9.10.2-P1-RedHat-9.10.2-2.P1.fc22 <<>> @127.0.0.1 A ns.dns.skydns.local
ns.dns.skydns.local.    60  IN  A   127.0.0.1
```

In Etcd:
```
$ etcdctl get /skydns/local/skydns/dns/ns/ns1
{ "host": "127.0.0.1" }
```

**Comment by Dynom** [comment]
Things are getting more weird by the minute..
I've just added a bogus record:
```
$ etcdctl set /skydns/local/skydns/foo/bar/bz1 '{"host": "127.0.0.1", "port": 1160, "ttl": 3600}'
{"host": "127.0.0.1", "port": 1160, "ttl": 3600}
```

And I get an immediate reply:
```
dig @127.0.0.1 A bar.foo.skydns.local

; <<>> DiG 9.10.2-P1-RedHat-9.10.2-2.P1.fc22 <<>> @127.0.0.1 A bar.foo.skydns.local
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 42589
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;bar.foo.skydns.local.		IN	A

;; ANSWER SECTION:
bar.foo.skydns.local.	3600	IN	A	127.0.0.1

;; Query time: 4 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Fri Jul 10 15:00:12 UTC 2015
;; MSG SIZE  rcvd: 54
```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[skydns] No answer on DNS query (#2..." ]
>I'm a noob when it comes to DNS and I can't seem SkyDNS to work.
>
>$ etcdctl get /skydns/local/skydns/hutsefluts/1
>{"host": "10.129.112.176", "ttl": "30", "targetstrip": 1 }
>```

ttl must be number, not a string:

```
./bin/etcdctl set /skydns/local/skydns/hutsefluts/1 '{"host":"10.129.112.176", "ttl": 30}'  

% dig @localhost -p 1053 a hutsefluts.skydns.local +short               
10.129.112.176

./bin/etcdctl set /skydns/local/skydns/hutsefluts/1 '{"host":"10.129.112.176", "ttl": "30"}'
dig @localhost -p 1053 a hutsefluts.skydns.local +short
<nothing>
```

And

```
% ./bin/etcdctl set /skydns/local/skydns/hutsefluts/1 '{"host":"10.129.112.176", "ttl": 30, "targetstrip":1}'
{"host":"10.129.112.176", "ttl": 30, "targetstrip":1}

% dig @localhost -p 1053 SRV hutsefluts.skydns.local                                                         

;; QUESTION SECTION:
;hutsefluts.skydns.local.       IN      SRV

;; ANSWER SECTION:
hutsefluts.skydns.local. 30     IN      SRV     10 100 0 hutsefluts.skydns.local.

;; ADDITIONAL SECTION:
1.hutsefluts.skydns.local. 30   IN      A       10.129.112.176
```

This returns an answer, but looking at it its wrong, that is a bug in
targetstrip.


/Miek

--
Miek Gieben

**Comment by Dynom** [comment]
For some reason there is something invalid why my automated scripts and my manual etcdctl commands:

The result of my provision scripts:
```
$ etcdctl ls --recursive /skydns/local/skydns/hutsefluts/
/skydns/local/skydns/hutsefluts/x6
/skydns/local/skydns/hutsefluts/x5
/skydns/local/skydns/hutsefluts/x1
...
```

And the query, results in no answer.
```
dig @127.0.0.1 A x1.hutsefluts.skydns.local

; <<>> DiG 9.10.2-P1-RedHat-9.10.2-2.P1.fc22 <<>> @127.0.0.1 A x1.hutsefluts.skydns.local
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 65340
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;x1.hutsefluts.skydns.local.	IN	A

;; AUTHORITY SECTION:
skydns.local.		60	IN	SOA	ns.dns.skydns.local. hostmaster.skydns.local. 1436540400 28800 7200 604800 60

;; Query time: 3 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Fri Jul 10 15:11:18 UTC 2015
;; MSG SIZE  rcvd: 98
```

Then I delete the records from Etcd.
```
$ etcdctl rm --recursive /skydns/local/skydns/hutsefluts
```

And I create one manually:
```
$ etcdctl set /skydns/local/skydns/hutsefluts/x1 '{"host": "8.8.8.8", "ttl": 30, "port": 12345, "targetstrip": 1}'
{"host": "8.8.8.8", "ttl": 30, "port": 12345, "targetstrip": 1}
```

And voila, the beast roars:
```
dig @127.0.0.1 A hutsefluts.skydns.local

; <<>> DiG 9.10.2-P1-RedHat-9.10.2-2.P1.fc22 <<>> @127.0.0.1 A hutsefluts.skydns.local
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 38764
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;hutsefluts.skydns.local.	IN	A

;; ANSWER SECTION:
hutsefluts.skydns.local. 30	IN	A	8.8.8.8

;; Query time: 8 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Fri Jul 10 15:12:53 UTC 2015
;; MSG SIZE  rcvd: 57
```

**Comment by Dynom** [comment]
The "automated scripts" is via systemd's unit files:
```
# SkyDNS settings
Environment="SKYDNS_ETCD_PATH=/skydns/local/skydns/%p/%i"
ExecStartPre=/usr/bin/etcdctl set "${SKYDNS_ETCD_PATH}" '{"host": "${COREOS_PRIVATE_IPV4}", "ttl": "30", "port": ${SERVICE_PORT} }'
ExecStop=/usr/bin/etcdctl rm "${SKYDNS_ETCD_PATH}"
```

Any pointers about what might be wrong? I'm guessing there is a bug in the JSON parser somewhere..

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [skydns] No answer on DNS query..." ]
>The "automated scripts" is via systemd's unit files:
>```
># SkyDNS settings
>Environment="SKYDNS_ETCD_PATH=/skydns/local/skydns/%p/%i"
>ExecStartPre=/usr/bin/etcdctl set "${SKYDNS_ETCD_PATH}" '{"host": "${COREOS_PRIVATE_IPV4}", "ttl": "30", "port": ${SERVICE_PORT} }'

ExecStartPre=/usr/bin/etcdctl set "${SKYDNS_ETCD_PATH}" '{"host": "${COREOS_PRIVATE_IPV4}", "ttl": 30, "port": ${SERVICE_PORT} }'

>ExecStop=/usr/bin/etcdctl rm "${SKYDNS_ETCD_PATH}"
>```

/Miek

--
Miek Gieben

**Comment by Dynom** [comment]
Holy shit.. I would've LOVED to get a parse-error notification, rather than a silent lookup fail...

**Comment by Dynom** [comment]
Thanks for the help @miekg, would you mind adding some logging on this part when the `-verbose` flag is specified? This might save someone a couple of hours in the future :-)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [skydns] No answer on DNS query..." ]
>Holy shit.. I would've LOVED to get a parse-error notification, rather than a silent lookup fail...

yeah... but this is not as trivial as it sounds, esp when returning multiple
entries and only one of those is not valid json. OTOH logging json validation
errors is a small fix.

/Miek

--
Miek Gieben

**Comment by Dynom** [comment]
Yeah, just any indication that there is something wrong with the JSON is good enough to help the search. I was looking in the total opposite direction: Firewalling, DNS config, Etcd2 problems, Docker problems, etc.

**Comment by Dynom** [comment]
Everything is looking fine now btw, all hosts reply and the performance seems pretty good. Thanks for your help and work on SkyDNS !

**Comment by miekg** [comment]
I've merged the logging branch, this should now be more obvious.

**Comment by Dynom** [comment]
excellent!
