### ISSUE TITLE
Request: Allow for automatic tagging of multiple instances.

### ISSUE THREAD

**Issue by dragonpaw** [skynetservices/skydns#207]
When populating SRV/A records, it would be nice if the final part could be dynamically assigned by skydns for IP records.

example:
- I want to spin up 4 identical workers based on an Amazon ec2 image.
- Each one registers an identical service to skydns such as 'http.example.com:80'
- DNS records end up as a.http.example.com - d.http.example.com, for ease of round robin.

This would be great to have since I don't realistically know how many of each service I'll have, and with auto-scaling in Amazon, the number changes over time automatically. And the individual machines have no way of knowing which is 'a' and which is 'c' (or 'x1' and 'x2' from your examples.) Depending on the load at any given moment I might have 2 instances of a service, or 20.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[skydns] Request: Allow for automat..." ]
>When populating SRV/A records, it would be nice if the final part could be dynamically assigned by skydns for IP records.

Sorry, but what is it exactly what skydns should do here? Should it expand some
magical host marker to an (dynamic) IP?

>example:
>- I want to spin up 4 identical workers based on an Amazon ec2 image.

ack.

>- Each one registers an identical service to skydns such as 'http.example.com:80'

who is doing this registration?

>- DNS records end up as a.http.example.com - d.http.example.com, for ease of round robin.

ack,

/Miek

--
Miek Gieben

**Comment by dragonpaw** [comment]
Let me see if I can explain the need better...

In Amazon AWS (and Docker/BlueOcean/etc) one can save a snapshot of a machine as an image meant for a specific use case, say a web server. That web server image might be for the main site of the prestigious hosting company, example.com. (They like to lead by example.) 

Now, in order to handle traffic intelligently, we have Amazon automatically scaling out the fleet of these web servers. So at night there is only 1-2 of them. But on Thursday when we get featured on Reddit, we automatically increased to 20 as traffic scaled up. (And then back down to 4 in the evening when people went home.)

Now, each of these machines were based off a pre-baked Amazon image, that knows it is supposed to help serve traffic for www.example.com, so within it is a beacon process that registers them with skydns when they start up, with a 100s TTL and cron job or small daemon that calls out to skydns every 60 seconds to register them when they start up, and removes them on shutdown. (Or on TTL expiration if the machine hard crashes, as they sometimes do.) 

But as I understand it, in order to use the wildcard query for www.example.com, the machines need to register themselves as xx.www.example.com where xx is a unique prefix for that specific host. ( https://github.com/skynetservices/skydns#wildcards ) 

And so there's basically a `curl -XPUT http://127.0.0.1:4001/v2/keys/skydns/com/example/www/xx \
    -d value='{"host":"1.2.3.4","port":80}'` getting called from within the host.


Now, my problem is that the hosts don't know how many siblings they have. So how does this job know to register itself as 1.www.example.com vs 40.www.example.com? 

Ideally I'd want to do something like:
`curl -XPUT http://127.0.0.1:4001/v2/keys/skydns/keys/skydns/com/example/www/* \
    -d value='{"host":"1.2.3.4","port":80}'` and get a response back that I was 13.www.example.com

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [skydns] Request: Allow for aut..." ]
>Let me see if I can explain the need better...
>
>But as I understand it, in order to use the wildcard query for www.example.com,
>the machines need to register themselves as xx.www.example.com where xx is a
>unique prefix for that specific host. (
>https://github.com/skynetservices/skydns#wildcards )
>
>And so there's basically a `curl -XPUT
>http://127.0.0.1:4001/v2/keys/skydns/com/example/www/xx \ -d
>value='{"host":"1.2.3.4","port":80}'` getting called from within the host.
>
>
>Now, my problem is that the hosts don't know how many siblings they have. So
>how does this job know to register itself as 1.www.example.com vs
>40.www.example.com?

So why are these hostnames numerical? Why not use something like
`uuidgen` and use that? SkyDNS does not care.

/Miek

--
Miek Gieben

**Comment by dragonpaw** [comment]
I feel that having these hostnames be 'human-friendly' is a benefit worth putting effort into. I don't care if they are numerical or a couple alphanumerics, like a.www... through q.www... for example. I'd prefer not to have to diagnose one of these hosts by doing `ssh 6fa459ea-ee8a-3ca4-894e-db77e160355e.www.example.com`

**Comment by miekg** [comment]
Ack. But this is not a job for SkyDNS. I suggest searching for something
random and short that decouples these hostnames from each other.
