### ISSUE TITLE
Refresh dns record

### ISSUE THREAD

**Issue by weekface** [skynetservices/skydns#214]
Now, skydns do not watch the etcd to update local cache.

I want to add a REST api: manual regenerate(refresh) local cache when the dns record change in the etcd.

```
$ curl http://host:port/refresh/local/skydns/service
```

any suggestion？

@miekg

**Comment by miekg** [comment]
The idea of SkyDNS(2) was to move all rest stuff out to etcd and only leave the DNS in skydns. Also with client side caching this does not update all the client at once.
