### ISSUE TITLE
ttl is not respected for service announcement request

### ISSUE THREAD

**Issue by anshulverma** [skynetservices/skydns#220]
I am seeing an odd behavior when I try to register a service with a smaller `ttl` value than the one in default config.

The registration request looks like this:
``` bash
curl -XPUT http://my.custom.etcd:4001/v2/keys/skydns/com/custom/it \
       -d value='{"host":"10.23.34.12", "ttl":1}'
```

If I understand correctly, this should set the TTL for `it.custom.com` to 1 minute. But, when I try to query this I get something entirely different:
``` bash
dig +nocmd +noall +answer it.custom.com
it.custom.com.         3600    IN      A       45.53.202.85
```

Seems like it picked the default setting (i.e. 3600) even though the one I passed was smaller.

**Comment by miekg** [comment]
No, you are setting the TTL to 1 second. Are you sure you are querying SkyDNS?

You might want to double the IP address you pasted..

**Comment by anshulverma** [comment]
@miekg thanks for pointing that out. I forgot to direct the query to the skydns server. Here is how the response looks like once I fixed it:

```bash
dig @my.custom.dns +nocmd +noall +answer it.custom.com
it.custom.com.         1    IN      A       10.23.34.12
```

The issue now is that the TTL seconds counter is not counting down (stays at 1). Am I missing something still?

**Comment by anshulverma** [comment]
OK. I think my understanding of the DNS server needs some refreshing. There is no issue here. The TTL is supposed to be used by caching servers to make sure the dns entry is expired after certain interval from its cache. So, as far as skydns is concerned, it will always hand out the same TTL value.

**Comment by anshulverma** [comment]
For anyone who is searching for a way to expire entries in skydns: you should set `ttl` on the etcd key directly. For example:

```bash
curl -XPUT http://my.custom.etcd:4001/v2/keys/skydns/com/custom/it \
       -d value='{"host":"10.23.34.12"}' \
       -d ttl=60
```

This will expire the entry after 60 seconds unless you send another heartbeat to update it.

**Comment by miekg** [comment]
Yep that's how to do it.
