### ISSUE TITLE
Setup fails with undefined: dns.PrivateKey

### ISSUE THREAD

**Issue by mwiora** [skynetservices/skydns#221]
Following the Setup Inscrutions in README.md I'm failing on
``` go get github.com/skynetservices/skydns ```

with

```
# github.com/skynetservices/skydns/server
$gopath/src/github.com/skynetservices/skydns/server/config.go:61: undefined: dns.PrivateKey
```
running on CentOS 7 and GO 1.4.1 - all existing packages updated to the latest version

The same happens unter Ubuntu 14.04.3 LTS and GO 1.5

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[skydns] Setup fails with undefined..." ]
>Following the Setup Inscrutions in README.md I'm failing on
>$ go get github.com/skynetservices/skydns
>
>with
>
>$gopath/src/github.com/skynetservices/skydns/server/config.go:61: undefined: dns.PrivateKey
># github.com/skynetservices/skydns/server
>running on CentOS 7 - all existing packages updated to the latest version

Ack. 

Yes, I made a breaking change in the DNSSEC part of go dns and this (of course)
break the compilation of SkyDNS. I will fix this soonish.

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[skydns] Setup fails with undefined..." ]
>Following the Setup Inscrutions in README.md I'm failing on
>$ go get github.com/skynetservices/skydns
>
>with
>
>$gopath/src/github.com/skynetservices/skydns/server/config.go:61: undefined: dns.PrivateKey
># github.com/skynetservices/skydns/server
>running on CentOS 7 - all existing packages updated to the latest version

Should now compile again.

/Miek

--
Miek Gieben

**Comment by mwiora** [comment]
works now for me! THX!
