### ISSUE TITLE
DNS Server Cache Snooping Remote Information Disclosure - Vulnerability identified  by scanner

### ISSUE THREAD

**Issue by bhairavi25** [skynetservices/skydns#222]
The following vulnerability was found on using SkyDNS by our vulnerability scanner `Nessus`.

***Content from Nessus scanner***
```
Description

The remote DNS server responds to queries for third-party domains that do not have the recursion bit set. 

This may allow a remote attacker to determine which domains have recently been resolved via this name server, and therefore which hosts have been recently visited. 

For instance, if an attacker was interested in whether your company utilizes the online services of a particular financial institution, they would be able to use this attack to build a statistical model regarding company usage of that financial institution. Of course, the attack can also be used to find B2B partners, web-surfing patterns, external mail servers, and more.

Note: If this is an internal DNS server not accessible to outside networks, attacks would be limited to the internal network. This may include employees, consultants and potentially users on a guest network or WiFi connection if supported.

Solution
Contact the vendor of the DNS software for a fix.
```

Following is the SkyDNS configuration that we use:
Skydns container is running on a docker container backed by etcd on another container.
etcd is setup with client-side certs and the config of skydns looks like this:

```
curl -XPUT --cacert <...ca-cert.pem> --cert <..client-cert.pem> --key <...-client-key.pem> https://<etcd-url>:4001/v2/keys/skydns/config -d value='{"dns_addr":"<ip>:53","ttl":3600,"domain":"skydns.local","nameservers": ["forwarder1:53","forwarder2:53"]}'
```
```
docker run -d -v /certs/:/etc/ssl/certs --name skydns --net host -e ETCD_MACHINES='https://etcd.docker.amm.ibmcloud.com:4001' -e ETCD_TLSKEY=...client-key.pem -e ETCD_TLSPEM=...client-cert.pem -e ETCD_CACERT=...ca-cert.pem skynetservices/skydns:latest
```

Can anyone help on fixing this vulnerability?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[skydns] DNS Server Cache Snooping ..." ]
>The following vulnerability was found on using SkyDNS by our vulnerability scanner `Nessus`.
>
>**Description**
>
>The remote DNS server responds to queries for third-party domains that do not have the recursion bit set.

Yes, it will just forward those to the upstream resolvers and return the answer.

>**Solution**
>Contact the vendor of the DNS software for a fix.

I think this is "works as intended", also by default SkyDNS does not cache
anything.

Any why is this only a problem when the RD bit is not set?

/Miek

--
Miek Gieben

**Comment by bhairavi25** [comment]
Appreciate your response.  Found the same vulnerability occurring even in google DNS servers and other public DNS servers so this issue is not specific to skydns. Hence closing this.
