### ISSUE TITLE
Make docker image trusted build

### ISSUE THREAD

**Issue by klausenbusk** [skynetservices/skydns#227]
Just a query to make the image on docker hub a trusted build.

**Comment by AdoHe** [comment]
@klausenbusk @miekg I think this is necessary and useful, it can keep our image up to date with our latest code.

**Comment by klausenbusk** [comment]
> @klausenbusk @miekg I think this is necessary and useful, it can keep our image up to date with our latest code.

Yes, but I think the Dockerfile need to be updated, for it to work. I will send a PR later.

**Comment by AdoHe** [comment]
@klausenbusk yes, I guess it doesn't have too much effort, we can refer this: `http://kimh.github.io/blog/en/docker/using-trusted-builds-to-generate-docker-image-automatically/`

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [skydns] Make docker image trus..." ]
>> @klausenbusk @miekg I think this is necessary and useful, it can keep our image up to date with our latest code.
>
>Yes, but I think the Dockerfile need to be updated, for it to work. I will send a PR later.

Can this work from the git tag we set? I.e. not 100% sure I want a new latest
image every time I push to master. For tags: yes I want an image with that tag.

/Miek

--
Miek Gieben

**Comment by klausenbusk** [comment]
> Can this work from the git tag we set?

Yes, but you need to add the tags manually http://stackoverflow.com/questions/25328166/docker-hub-automated-build-tagging

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [skydns] Make docker image trus..." ]
>> Can this work from the git tag we set?
>
>Yes, but you need to add the tags manually http://stackoverflow.com/questions/25328166/docker-hub-automated-build-tagging

so I need to tag -> push -> go to website -> set tag ?

If so, that's not really automated...

/Miek

--
Miek Gieben

**Comment by klausenbusk** [comment]
> If so, that's not really automated...

Nope, I through it was more automated. :/
Also for the tagging to work, the Dockerfile need to download that specific tag with git. It a mess.
Maybe we should just close this issue? Through I will prefer that the Dockerfile can build the binary alone (new issue maybe?).

The binary can be built like this: https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/issues/62

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [skydns] Make docker image trus..." ]
>> If so, that's not really automated...
>
>Nope, I through it was more automated. :/
>Also for the tagging to work, the Dockerfile need to download that specific tag with git. It a mess.

Yeah, please close this issue. If I can't get docker to automatically build from
specific tags and use those in the dockerfile tagging, is is pretty useless.
It also can't build from makefile, so my supersmall docker images needs to
baloon to build skydns in the image (or something).

/Miek

--
Miek Gieben

**Comment by klausenbusk** [comment]
> so my supersmall docker images needs to baloon to build skydns in the image (or something).

It don't. See my link, you can do something similar: https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/issues/62
I close this issue.
