### ISSUE TITLE
support for etcd authentication 

### ISSUE THREAD

**Issue by nebelpfade** [skynetservices/skydns#228]
any plans for support this feature:
https://github.com/coreos/etcd/blob/master/Documentation/authentication.md

**Comment by AdoHe** [comment]
@nebelpfade this is just an experimental feature, also from the etcd source code this feature is still not so complete.

**Comment by nebelpfade** [comment]
Google Kubernetes team are working on support already:
https://github.com/kubernetes/kubernetes/issues/11962

Also there is new etcd client:
github.com/coreos/etcd/client
which supports it already.

**Comment by AdoHe** [comment]
@nebelpfade yeah, I know this, if so we can do this.

**Comment by raoofm** [comment]
@AdoHe @nebelpfade Any timelines yet for supporting auth feature?

**Comment by AdoHe** [comment]
@raoofm I will do this as soon as I can.

**Comment by wikiwi** [comment]
:+1:

**Comment by nebelpfade** [comment]
Just for your information, kubernetes team completed etcd auth:

**Comment by AdoHe** [comment]
@nebelpfade I will do this during this week.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [skydns] support for etcd authe..." ]
>@nebelpfade I will do this during this week.

Cool! SkyDNS also still uses the old (legacy) etcd api, I am assuming you port
it to the new one as well? (think this is a necessity for auth).

/Miek

--
Miek Gieben

**Comment by AdoHe** [comment]
@miekg yeap, I will port it to the new one. And I will open a PR during this week.

**Comment by ysh7** [comment]
@AdoHe is this issued fixed with new etcd client?  @miekg we still don't flag/config to make it work with skydns

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [skydns] support for etcd authe..." ]
>@AdoHe is this issued fixed with new etcd client? 

Nope.

> @miekg we still don't flag/config to make it work with skydns

Nope.

PRs welcome about this though.

/Miek

--
Miek Gieben

**Comment by AdoHe** [comment]
@miekg @ysh7 I will send a PR to fix this.

**Comment by ysh7** [comment]
@AdoHe ping!

**Comment by AdoHe** [comment]
@ysh7 I think the new etcd client now support secured etcd cluster. I will add test later.

**Comment by AdoHe** [comment]
I think I have already fixed this on my local, I just forget to push this to github.

**Comment by DerekTBrown** [comment]
@AdoHe any chance we could get you to submit a PR with that authentication code?

**Comment by AdoHe** [comment]
I have opened a PR #289 to fix this, @DerekTBrown @nebelpfade @miekg ptal.

**Comment by DerekTBrown** [comment]
:)
