### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by luxas** [skynetservices/skydns#233]
Hello,
Today I tried to build skydns like I've done earlier, and it failed.
Please fix it, although it is another repo that throws the error

```
CGO_ENABLED=0 go get -a -installsuffix cgo --ldflags '-w' github.com/skynetservices/skydns
# github.com/ugorji/go/codec
gopath/src/github.com/ugorji/go/codec/fast-path.generated.go:1824: v declared and not used
```

**Comment by luxas** [comment]
Well, now it's fixed, but I should have appreciated some answer :/

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [skydns] Build issue (#233)..." ]
>Well, now it's fixed, but I should have appreciated some answer :/

upstream package(s) messing with their stuff. At some point I will
vender the deps for SkyDNS.


/Miek

--
Miek Gieben
