### ISSUE TITLE
Cannot do nslookup on the first part of the FQDN through Skydns

### ISSUE THREAD

**Issue by JGPT** [skynetservices/skydns#236]
Hello,

After installed skydns and followed the steps in
https://github.com/kubernetes/kubernetes/blob/v1.0.6/cluster/addons/dns/README.md#how-do-i-configure-it  (especially, ReplicationController and Service), 

we are able to do nslookup for FQDN 
kubectl exec busybox -- nslookup kubernetes.default.svc.kube.local

but not first part of the FQDN
kubectl exec busybox -- nslookup kubernetes

The search list is added to /etc/resolv.conf.
search default.svc.kube.local svc.kube.local kube.local
options ndots:5

But it still does not help.

Appreciate your help.

Detail:
kubectl exec busybox -- nslookup kubernetes.default.svc.kube.local
Server:    10.100.0.10
Address 1: 10.100.0.10

Name:      kubernetes.default.svc.kube.local
Address 1: 10.100.0.1

kubectl exec busybox -- nslookup kubernetes
Server:    10.100.0.10
Address 1: 10.100.0.10

nslookup: can't resolve 'kubernetes'
error: Error executing remote command: Error executing command in container: Error executing in Docker Container: 1

Here is the skydns-rc.yaml  (mainly the same as 

cat skydns-rc.yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-dns-v8
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    version: v8
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: kube-dns
    version: v8
  template:
    metadata:
      labels:
        k8s-app: kube-dns
        version: v8
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: etcd
        image: gcr.io/google_containers/etcd:2.0.9
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        command:
        - /usr/local/bin/etcd
        - -data-dir
        - /var/etcd/data
        - -listen-client-urls
        - http://127.0.0.1:2379,http://127.0.0.1:4001
        - -advertise-client-urls
        - http://127.0.0.1:2379,http://127.0.0.1:4001
        - -initial-cluster-token
        - skydns-etcd
        volumeMounts:
        - name: etcd-storage
          mountPath: /var/etcd/data
      - name: kube2sky
        image: gcr.io/google_containers/kube2sky:1.11
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        args:
        # command = "/kube2sky"
        - -domain=kube.local
        - -kube_master_url=http://159.203.244.226:8080
      - name: skydns
        image: skynetservices/skydns:latest
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        args:
        # command = "/skydns"
        - -machines=http://localhost:4001
        - -addr=0.0.0.0:53
        - -domain=kube.local
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
      - name: healthz
        image: gcr.io/google_containers/exechealthz:1.0
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
        args:
        - -cmd=nslookup kubernetes.default.svc.kube.local localhost >/dev/null
        - -port=8080
        ports:
        - containerPort: 8080
          protocol: TCP
      volumes:
      - name: etcd-storage
        emptyDir: {}
      dnsPolicy: Default  # Don't use cluster DNS.

Here is skydns-svc.yaml

cat  skydns-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: kube-dns
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "KubeDNS"
spec:
  selector:
    k8s-app: kube-dns
  clusterIP: 10.100.0.10
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP

 cat /etc/resolv.conf
# Generated by NetworkManager
nameserver 8.8.8.8
nameserver 8.8.4.4
search default.svc.kube.local svc.kube.local kube.local
options ndots:5
----

Thanks,

Jim

**Comment by miekg** [comment]
I don't know the ins and outs of kubernetes. Sorry.
