### ISSUE TITLE
can not build skydns 

### ISSUE THREAD

**Issue by lostz** [skynetservices/skydns#237]
go build -v
get many errors 
../../coreos/go-etcd/etcd/response.generated.go:61: z.HasExtensions undefined (type codec.genHelperEncoder has no field or method HasExtensions)
use godep?
or use official  etcd Go client ?

**Comment by miekg** [comment]
prolly will move to gb (if anything), pondering though if I want to include something as large as etcd, *and* I do want to follow upstream etcd pretty close...

**Comment by miekg** [comment]
Can't repro (today):
```
% git pl
Already up-to-date.
% go get -u -f
% rm -rf ../../coreos/
% go get -u -f
12.70s user 1.74s system 25.26s elapsed 57%CPU ()
% go build
```
