### ISSUE TITLE
Zone transfer

### ISSUE THREAD

**Issue by macpoint** [skynetservices/skydns#239]
Hi,
I am running skydns via kubernetes in docker container and I would like to have my zone transferred to a secondary DNS server running bind. I have noticed that miekg/dns supports AXFR/IXFR queries but when trying to query my skydns ns I get a failure:

    $ host -t axfr mydomain.io 172.17.0.65

    Trying "mydomain.io"
    Using domain server:
    Name: 172.17.0.65
    Address: 172.17.0.65#53
    Aliases:

    ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 65330
    ;; flags: qr aa ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

    ;; QUESTION SECTION:
    ;mydomain.io.				IN	AXFR

    ;; AUTHORITY SECTION:
    mydomain.io.			60	IN	SOA	ns.dns.mydomain.io. hostmaster.skydns.local. 1448539200 28800 7200 604800 60

    ; Transfer failed.

Is zone transfer enabled in skydns?

Thanks

**Comment by miekg** [comment]
No skydns does not support transfers atm. As everything is dynamically generated what should be transferred when other nameservers ask for an axfr? (genuine questions, I don't know). If we can answer this, enabling [ai]xfr in skydns is trivial.

**Comment by miekg** [comment]
I really don't know how skydns can support axfr....

**Comment by joaquin386** [comment]
Was looking for the same thing. Looking but do not find anything.
