### ISSUE TITLE
Update skydns to latest etcd api

### ISSUE THREAD

**Issue by miekg** [skynetservices/skydns#240]
Skydns should use the "new" api.

**Comment by AdoHe** [comment]
@miekg I have finished this code, and am doing test in our cluster.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [skydns] Update skydns to lates..." ]
>@miekg I have finished this code, and am doing test in our cluster.

Nice! And thank you!

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
@AdoHe how did the tests go? Anything ready to be merged?

Thanks!

**Comment by AdoHe** [comment]
@miekg I am so sorry about reply you so late, I will open a PR before this weekend. Really sorry about that.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [skydns] Update skydns to lates..." ]
>@miekg I am so sorry about reply you so late, I will open a PR before this weekend. Really sorry about that.

No worries, I was just wondering.

Thanks!

**Comment by miekg** [comment]
ping?

**Comment by AdoHe** [comment]
Hi miekg, would you mind reviewing this PR #245? Thanks very much :)

**Comment by fastest963** [comment]
@miekg this can be closed since #245 via #246 was merged?
