### ISSUE TITLE
SkyDNS in Kubernetes: SERVFAIL response when connecting through OpenVPN Pod

### ISSUE THREAD

**Issue by streamnsight** [skynetservices/skydns#243]
Sorry if this is not the right place, but I think it is:

I work on a kubernetes cluster. In order to locally debug services that depend on other services in the cluster, I setup a VPN server in the cluster and connect from local client.

Kubernetes uses SkyDNS for DNS within the cluster. This works fine. 
From any Pod inside the cluster I can `nslookup` my services and get an IP resolved.

However when I connect through the VPN this fails.

VPN subnet is `10.8.0.0/24`
I have routes setup on the VPN server to route traffic to the Pod and Service subnets
- I can ping the Pods (`subnet 10.2.0.0/16`)
- I can ping the Services (`subnet 10.3.0.0/16`) and the DNS IP (`10.3.0.10`, on the same subnet)
- I can query my Services by IP and get data, so the requests and responses go through.

SkyDNS IP (`10.3.0.10`) is first on my resolution list, but `nslookup` from the VPN client returns:

```
nslookup kubernetes
;; Got recursion not available from 10.3.0.10, trying next server
;; Got SERVFAIL reply from 10.3.0.10, trying next server
...
```

How do I troubleshoot this?

Thanks for help

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[skydns] SkyDNS in Kubernetes: SERV..." ]
>Sorry if this is not the right place, but I think it is:
>
>I work on a kubernetes cluster In order to locally debug services that depend on other services in the cluster, I setup a VPN server in the cluster and connect from local client
>
>Kubernetes uses SkyDNS for DNS within the cluster This works fine
>From any Pod inside the cluster I can `nslookup` my services and get an IP resolved
>
>However when I connect through the VPN this fails
>
>VPN subnet is `10800/24`
>I have routes setup on the VPN server to route traffic to the Pod and Service subnets
>- I can ping the Pods (`subnet 10200/16`)
>- I can ping the Services (`subnet 10300/16`) and the DNS IP (`103010`, on the same subnet)
>- I can query my Services by IP and get data, so the requests and responses go through
>
>SkyDNS IP (`103010`) is first on my resolution list, but `nslookup` from the VPN client returns:
>
>```
>nslookup kubernetes
>;; Got recursion not available from 103010, trying next server
>;; Got SERVFAIL reply from 103010, trying next server
>
>```
>
>How do I troubleshoot this?

Please debug dns issues with dig ;-)
Think you might also need tcpdump to see where requests end up. My initial guess
would be that skydns is not routing returns requests properly in this case.

So dump on the skydns instance (all interfaces port 53) and try to spot your
query and response it gives.

/Miek

--
Miek Gieben

**Comment by streamnsight** [comment]
@miek 
thanks.
after much digging i found that it was because the vpn server was not pushing the search domains to the client.
interestingly though, dig works but ping or traceroute did not. 
and curl didn't work at first but somehow starts resolving names after several seconds.
go figure...

**Comment by streamnsight** [comment]
@miek 
thanks.
after much digging i found that it was because the vpn server was not pushing the search domains to the client.
interestingly though, dig works but ping or traceroute did not. 
and curl didn't work at first but somehow starts resolving names after several seconds.
go figure...

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [skydns] SkyDNS in Kubernetes: ..." ]
>@miek
>thanks.
>after much digging i found that it was because the vpn server was not pushing the search domains to the client.
>interestingly though, dig works but ping or traceroute did not.

dig does not use the search domains, ping and traceroute do (via libc).

>and curl didn't work at first but somehow starts resolving names after several seconds.
>go figure...
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/skynetservices/skydns/issues/243#issuecomment-173243022
/Miek

--
Miek Gieben

**Comment by gtmtech** [comment]
dig uses search domains if you specify the +search flag
