### ISSUE TITLE
CLI flag for version info

### ISSUE THREAD

**Issue by ysh7** [skynetservices/skydns#247]
Currently there is no way to get the version of build skydns binary. Is it possible to have a version flag which gives version information ?

**EDIT:** Something like etcd maybe, will be great?
```
$ etcd --version
etcd Version: 2.2.5
Git SHA: bc9ddf2
Go Version: go1.5.3
Go OS/Arch: darwin/amd64
```

**Comment by AdoHe** [comment]
Guess so I will add this.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [skydns] CLI flag for version i..." ]
>Guess so I will add this.

Fine by me :) Send a PR :)

**Comment by AdoHe** [comment]
I just return from my new year holiday and will add this tomorrow.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [skydns] CLI flag for version i..." ]
>I just return from my new year holiday and will add this tomorrow.

Note that SkyDNS implements version.bind and version.server, so in that sense
it does not *really* need a cli flag, although that is convenient.

/Miek

--
Miek Gieben

**Comment by AdoHe** [comment]
@miekg I just send a PR #251, as SkyDNS implements version.bind and version.server, this flag is just for convenience, so it just print the SkyDNS server version. Would you mind reviewing this?

**Comment by ysh7** [comment]
@miekg looks you have merged the PR, closing this issue.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [skydns] CLI flag for version i..." ]
>@miekg looks you have merged the PR, closing this issue.
ack.
