### ISSUE TITLE
Does skydns support active-active deployments?

### ISSUE THREAD

**Issue by timothysc** [skynetservices/skydns#256]
I have a kubernetes cluster where we've load-balanced our dns resolution for our cluster and we're seeing inconsistent name resolution.  So I guess my question is, does skydns sync it's state from changes in etcd to support active-active / load-balanced (sky-dns) instances?  

/cc @rrati

**Comment by miekg** [comment]
There is no syning, SkyDNS will to go etcd for every query it gets, if etcd is in sync skydns is in sync. *However* some application might hold on to the answer from SkyDNS? (TTL too long?)
