### ISSUE TITLE
Add pre-built binaries to releases

### ISSUE THREAD

**Issue by zweizeichen** [skynetservices/skydns#273]
Hey there,
it would be great if we had pre-baked binaries e.g. for use on CoreOS in the releases. This greatly facilitates deployment as you don't have to build the project yourself.

**Comment by miekg** [comment]
On coreos? You'll prolly want to use docker there?

Right now, releasing is setting a tag in git, not looking forward to do more than that.

**Comment by zweizeichen** [comment]
Yeah - missed that. I wanted to use skyDNS outside the Kubernetes context. You're right, Docker kinda acts as the 'missing package manager' for CoreOS apart from some non-containerized stuff like (most of the time) the kubelet or e.g. Calico networking plugins. Guess that's where my confusion came from, as I wanted to run skyDNS 'outside' the Kubernetes cluster i.e. in a non-containerized way while I just could have used a simple Docker container not managed by Kubernetes - instead being invoked by systemd - as well.

PS: seems like the latest-tagged image mentioned in the readme is missing on Docker Hub
