### ISSUE TITLE
Falling back to default configuration

### ISSUE THREAD

**Issue by colonelmo** [skynetservices/skydns#276]
I believe [this](https://github.com/skynetservices/skydns/blob/master/main.go#L178) behavior is quite unnecessary. We are using skydns for internal node discovery and this is constantly getting us into trouble and kubernetes minions continuously stop working since the skydns server that they query for api server's ip has suddenly decided to fall back to default configuration after a say, restart. I believe being able to query etcd is a must and any other configuration which contradicts the crucial need for etcd has to be passed in explicitly e.g.  using command line arguments, and skydns would be better off just exiting with non-zero code or keep querying etcd at that point.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[skynetservices/skydns] Falling bac..." ]
>I believe [this](https://github.com/skynetservices/skydns/blob/master/main.go#L178) behavior is quite unnecessary. We are using skydns for internal node discovery and this is constantly getting us into trouble and kubernetes minions continuously stop working since the skydns server that they query for api server's ip has suddenly decided to fall back to default configuration after a say, restart. I believe being able to query etcd is a must and any other configuration which contradicts the crucial need for etcd has to be passed in explicitly e.g.  using command line arguments, and skydns would be better off just exiting with non-zero code or keep querying etcd at that point.

I agree, that is indeed not helpful.

How easy is it for you to switch to CoreDNS (github.com/miekg/coredns)? That
should fix this behavior and I am anxious get to some real-world feedback on how
it works in such environments. It should be a drop-in replacement.

**Comment by colonelmo** [comment]
Thanks for the quick response. I'll let you know as soon as we get a chance to check it out.
