### ISSUE TITLE
Inquiry: read udp i/o timeouts

### ISSUE THREAD

**Issue by fbdlampayan** [skynetservices/skydns#300]
Hi!

Cloned a clean copy of the master skydns, did the proper setup and build the project succesfully.
Tried to run the tests like what was being done in the travis build script
"go test -tags etcd -bench=. ./..."

However the tests fails in my local environment, specifically the errors are all similar like:
read udp 127.0.0.1:46282->127.0.0.1:9460: i/o timeout
or
skydns: failure to forward request "read udp 10.0.2.15:35234->8.8.4.4:53: i/o timeout"
skydns: failure to forward stub request "read udp 10.0.2.15:44326->199.43.132.53:53: i/o timeout"

Am I missing something in my local setup?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[skynetservices/skydns] Inquiry: re..." ]
>Hi!
>
>Cloned a clean copy of the master skydns, did the proper setup and build the project succesfully.
>Tried to run the tests like what was being done in the travis build script
>"go test -tags etcd -bench=. ./..."
>
>However the tests fails in my local environment, specifically the errors are all similar like:
>read udp 127.0.0.1:46282->127.0.0.1:9460: i/o timeout
>or
>skydns: failure to forward request "read udp 10.0.2.15:35234->8.8.4.4:53: i/o timeout"
>skydns: failure to forward stub request "read udp 10.0.2.15:44326->199.43.132.53:53: i/o timeout"
>
>Am I missing something in my local setup?

No probably not. I've seen these errors from time-to-time in Travis as well and
never got to the bottom of them :(

Could you try [CoreDNS](https://github.com/miekg/coredns) and see if you see
similar stuff?

Thanks!

**Comment by fbdlampayan** [comment]
Ahhh so it is a known problem.
Okay then I guess I should let it go for now, will proceed with my modifications.
We can close this issue. :)


About coredns:
Tried it but wasn't able to properly build it.
Did cloning via git then "go get -v ./...", and even via "go get github.com/miekg/coredns"
Both yielded the same errors:

In go get something like:
can't load package: package k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/cache: code in directory /home/ubuntu/Desktop/work/coredns/src/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/cache expects import "k8s.io/client-go/tools/cache"

And in building it ends with:
# github.com/miekg/coredns/middleware/kubernetes
middleware/kubernetes/controller.go:34: undefined: "k8s.io/kubernetes/pkg/client/unversioned".Client

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [skynetservices/skydns] Inquiry..." ]
>Ahhh so it is a known problem.
>Okay then I guess I should let it go for now, will proceed with my modifications.
>We can close this issue. :)
>
>
>About coredns:
>Tried it but wasn't able to properly build it.
>Did cloning via git then "go get -v ./...", and even via "go get github.com/miekg/coredns"
>Both yielded the same errors:
>
>In go get something like:
>can't load package: package k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/cache: code in directory /home/ubuntu/Desktop/work/coredns/src/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/cache expects import "k8s.io/client-go/tools/cache"
>
>And in building it ends with:
># github.com/miekg/coredns/middleware/kubernetes
>middleware/kubernetes/controller.go:34: undefined: "k8s.io/kubernetes/pkg/client/unversioned".Client

Yes, we are aware of that - k8s is redoing their interface atm :/ You could
download the CoreDNS binary.

**Comment by fbdlampayan** [comment]
> Yes, we are aware of that - k8s is redoing their interface atm :/ You could
> download the CoreDNS binary.

Alright! 
Anyways I'd be closing this issue now. Thanks for the info!
