### ISSUE TITLE
Why skydns not support ptr records in dir

### ISSUE THREAD

**Issue by gwtony** [skynetservices/skydns#303]
I need to add ptr records like:
1.1.1.1 <-> mysql.test.com
1.1.1.1 <-> redis.test.com
becase there are two services in ip 1.1.1.1

but it seems like skydns does not support ptr records in this way
In  code, it comments "must be only one service record"
Why one ip only binds to one name ？

 Thank you

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[skynetservices/skydns] Why skydns ..." ]
>I need to add ptr records like:
>1.1.1.1 <-> mysql.test.com
>1.1.1.1 <-> redis.test.com
>becase there are two services in ip 1.1.1.1
>
>but it seems like skydns does not support ptr records in this way
>In  code, it comments "must be only one service record"
>Why one ip only binds to one name ？

http://serverfault.com/a/618775

For CoreDNS (https://github.com/miekg/coredns) I decided not to care.


/Miek

--
Miek Gieben

**Comment by gwtony** [comment]
Thank you, maybe i will try coredns
