### ISSUE TITLE
add skydock functionality directly in skydns?

### ISSUE THREAD

**Issue by miekg** [skynetservices/skydns#94]
With kubernetes support we write into etcd. This is new functionality for SkyDNS, but now that we do it, well can (ans should probably) also incorporate skydock func. into SkyDNS.

**Comment by miekg** [comment]
We're removing kubernetes supports, which I assume just write to ectd now? (Didn't look at the code). If so I so no reason to fix *this* issue. That way skydns can stay lean and mean and just do DNS.

**Comment by bketelsen** [comment]
agreed - closing
