### ISSUE TITLE
Why are ANY queries rejected?

### ISSUE THREAD

**Issue by sheldonh** [skynetservices/skydns#97]
Commit 42b8e43c:

```
commit 42b8e43cc1ae3b87f9284734f781dcff8ba515cc
Author: Miek Gieben <miek@miek.nl>
Date:   Wed Jul 30 11:01:02 2014 +0000

    Dont answer ANY queries; return refused
```

The source code offers this explanation:

```
// fuck ANY queries
```

Could someone clarify? It's pretty natural to use ANY queries for service discovery, rather than "try SRV, then try CNAME, then try A".

**Comment by miekg** [comment]
[This](https://bugzilla.mozilla.org/show_bug.cgi?id=1137628) sums up some of reason. IMO someone should just write the RFC to deprecate ANY altogether.

**Comment by sheldonh** [comment]
The referenced article describes how ANY is useless against a recursive
server. Sure. There are lots of useless ways to use dns.

But what about the case where you're using SkyDNS as an authoritative
server?

I'm not seeing how that article sums up why SkyDNS refuses ANY always.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [skydns] Why are ANY queries re..." ]
>The referenced article describes how ANY is useless against a recursive
>server. Sure. There are lots of useless ways to use dns.
>
>But what about the case where you're using SkyDNS as an authoritative
>server?
>
>I'm not seeing how that article sums up why SkyDNS refuses ANY always.

ANY is a stupid idea that made sense, well never.

If you want both A and AAAA in one go you should standardize the meta
RR type for that. ANY is not the replacement for this.

**Comment by sheldonh** [comment]
I'm not sure where you got the idea that I wanted ANY for ipv6. I wanted it
for A or SRV.

I can live without it. I was just hoping to learn why, because I've
struggled to find clear motivation against its value (I.e. the RFC you wish
someone would write). :-)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [skydns] Why are ANY queries re..." ]
>I'm not sure where you got the idea that I wanted ANY for ipv6. I wanted it
>for A or SRV.

Hmmm, so this *only* works if you hit SkyDNS directly. If you have
any chance of hitting an intermediate cache you can't be sure to get both
records. A local dnsmasq can throw a monkey wrench in your plan.

>I can live without it. I was just hoping to learn why, because I've
>struggled to find clear motivation against its value (I.e. the RFC you wish
>someone would write). :-)

I sympathise with the latency argument. But this is why everybody is prefetching and
parallel fetching DNS data.

**Comment by sheldonh** [comment]
I guess I tunnel-visioned on SkyDNS in a specific role, the service that docker containers in a CoreOS cluster use as the authoritative service for their own domain. That's really tying down a protocol to a very small use case, and so unwise.

Thanks!
